### ISSUE TITLE
Inline method name  parallelTo in actions is to long

### ISSUE THREAD

**Issue by icefill** [libktx/ktx#102]
I know it was libgdxs original method name,
But like sequence method is changed to 'then', I wish parallelTo change its name like 'with' or something like more less verborse

**Comment by czyzby** [comment]
`then` is pretty much self-descriptive - invoke an action _after_ this one. I don't think `with` is a good alias in this case, and I honestly have no idea what we could use instead. `parallelTo` is not _that_ verbose, I think. If `with` works for you, add your custom extension method - look through the `ktx-actors` sources to see how it was implemented.

**Comment by icefill** [comment]
Wow that's fast response but little bit sad.. Anyway,  I already saw your sources. Thank you for your wonderful work.

**Comment by czyzby** [comment]
All suggestions are welcome of course, but we do care about the readability and consistency between modules. KTX function names should be obvious at first glance. If you can find a shorter, self-descriptive equivalent of `parallelTo`, we can add it as well - pull requests are welcome. For now, I'm closing the issue. Thanks.

**Comment by czyzby** [comment]
`parallelTo` was renamed to `along` along the way. :)
