### ISSUE TITLE
inline to create entity in ashley's engine throws exception

### ISSUE THREAD

**Issue by erez-avidan** [libktx/ktx#105]
when doing something like so:
```
engine.entity {
           with<BodyComp> {
     }
}
```

you get this exception:
Caused by: java.lang.NoSuchMethodError: com.badlogic.ashley.core.Engine.createEntity()Lcom/badlogic/ashley/core/Entity;

probably because of commit 8f6c8e9
where you used to use method "createEntity" on PooledEngine but changed it to Engine which doesn't have this method

**Comment by Jkly** [comment]
@erez-avidan What version of Ashley are you using? `Engine.createEntity` was introduced in Ashley 1.7.3 https://github.com/libgdx/ashley/releases/tag/ashley-1.7.3

**Comment by erez-avidan** [comment]
true. my bad
