### ISSUE TITLE
Is ktx/ashley meant to be used?

### ISSUE THREAD

**Issue by JasonKDarby** [libktx/ktx#106]
I see ashley is not in the list of current KTX modules though version 1.7.3 is available.  Should I not be trying to use it for now?

Thanks!

**Comment by czyzby** [comment]
You should definitely try using it if you're working with Ashley and KTX. It's just that the `README.md` file was not updated - thanks for bringing it up.

**Comment by czyzby** [comment]
Fixed. Thanks.
