### ISSUE TITLE
Update to LibGDX 1.9.7.

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#108]

**Comment by czyzby** [comment]
Blocked by: https://github.com/libgdx/libgdx/issues/4960 - Box2D module tests fail. @Jkly Should we release next beta with the relevant Box2D tests ignored?

**Comment by czyzby** [comment]
I guess we'll release the next beta version without `ChainShape` support - anyone using LibGDX 1.9.7 might still appreciate the up-to-date KTX version.

**Comment by Jkly** [comment]
Yes ignoring those tests seems reasonable.
