### ISSUE TITLE
Improve collections module tests

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#109]
The test cases in the collections module were not refactored, and some of the tests are inconsistent with other KTX modules - for example, they use `camelCase` method names rather than `` `readable Kotlin syntax` ``. While this is not a pressing issue, tests should be consistent throughout the project.

**Comment by nukesz** [comment]
Created PR #147

**Comment by czyzby** [comment]
Thanks @nukesz, that's a great contribution!

**Comment by czyzby** [comment]
I think `vis` is the only module that might need some improvements as far as testing goes. Thanks again!
