### ISSUE TITLE
Question: Mix of Class<out Type> and KClass<out Type>?

### ISSUE THREAD

**Issue by TomGrill** [libktx/ktx#124]
Is there a certain reason when Class and when KClass is used? Should'nt it be KClass only in a kotlin project?

**Comment by czyzby** [comment]
Yeah, I agree that KClasses should be used instead to simplify the API for our users. I might have just overlooked it at the time. If you don't mind refactoring the `ktx-inject` module, you can change most of the `Class` usages to `KClass` (except for [this map](https://github.com/libktx/ktx/blob/master/inject/src/main/kotlin/ktx/inject/inject.kt#L27)) - I actually thought about this immediately when I was reviewing your PR.

**Comment by czyzby** [comment]
I've modified methods that were considered public API and consumed `Class` instances instead of `KClass`. The `ktx-inject` API should be less verbose now.
