### ISSUE TITLE
ShapeRenderer.use

### ISSUE THREAD

**Issue by keturn** [libktx/ktx#162]
The GDX ShapeRenderer has `begin` and `end` methods. Should we make the ktx-graphics version have a `use` block, the same way Batch and ShaderProgram do?

**Comment by czyzby** [comment]
Sure. We just make sure to add the `ShapeType` parameter. Do you want to add this utility in a PR or should I implement it?

**Comment by keturn** [comment]
Yeah, I expect I'll be able to make a PR for this.

**Comment by czyzby** [comment]
Thanks for the PR, @keturn.
