### ISSUE TITLE
Update to LibGDX 1.9.9

### ISSUE THREAD

**Issue by CreamyCookie** [libktx/ktx#168]
1.9.9 is out: https://github.com/libgdx/libgdx/issues/5306#issuecomment-439159885

btw. Thank you for this set of great libraries! :+1:

**Comment by czyzby** [comment]
`ktx-vis` fails to compile after updating to 1.9.9. See https://github.com/kotcrab/vis-editor/issues/275. @kotcrab 

Will ignore some tests and add deprecations as a temporary workaround.

**Comment by czyzby** [comment]
`1.9.9-SNAPSHOT` version is being uploaded as I'm writing this comment. I encourage the voters to test the new release. @demoth @lokeshj @jcornaz ;)

I'm going to leave this open for now, as we want to wait for the new VisUI release.

**Comment by kotcrab** [comment]
@czyzby I've uploaded VisUI 1.4.2 for libGDX 1.9.9.

**Comment by czyzby** [comment]
Done. KTX `1.9.9-SNAPSHOT` should work with Kotlin `1.3.11`, LibGDX `1.9.9` and VisUI `1.4.2`.

**Comment by CreamyCookie** [comment]
@kotcrab  @czyzby Thanks! =)
