### ISSUE TITLE
The `+` operator should not mutate its receiver

### ISSUE THREAD

**Issue by jcornaz** [libktx/ktx#171]
Please consider the following code:

```kotlin
val stage1 = Stage()
val stage2 = stage1 + MyActor() // <-- Surprise it adds an actor to stage1
```

Usually we don't expect `+` to mutate anything. Kotlin provides explicit operators for mutation (in this case `+=`).

I propose to deprecate that `+` operator and introduce the `+=` alternative (when adding actor to stage, but also when adding actions to actor)

**Comment by jcornaz** [comment]
In the other hand a `+` operator to create a sequence of actions would be nice:

```kotlin
val sequence = moveTo(200, 200, 0.5f) + rotateTo(90, 0.5f) + fadeOut(0.5f) + remove()
```

But still, the `+` operator in this case would be pure.

Should I create a separate issue for this latest proposal?

**Comment by czyzby** [comment]
> Usually we don't expect `+` to mutate anything

Yes, this is oversight on my part.

> Should I create a separate issue for this latest proposal?

Sure, if you don't mind.
