### ISSUE TITLE
Updating Spek tests

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#173]
JUnit platform Gradle plugin is [deprecated](https://junit.org/junit5/docs/current/user-guide/#running-tests-build) as of `1.2.0` and Spek2 seems to rely on other APIs.

@Jkly Would you attempt updating or rewriting Spek tests in the `ktx-ashley` module? I don't mind updating to Spek2 release candidate or going with a different testing framework altogether.

**Comment by Jkly** [comment]
Sure I can take a look - I think it should be a case of using the built-in Junit platform now in Gradle (if you don't mind if we stay on Spek 1 for now).

**Comment by czyzby** [comment]
This is OK.

**Comment by czyzby** [comment]
Thanks @Jkly.
