### ISSUE TITLE
ArrayMap does not support square bracket assignment

### ISSUE THREAD

**Issue by limbusdev** [libktx/ktx#176]
Hi,
great extension to libGDX :) thank you for that.

My question: how can square brackets be used with libKTX ArrayMaps?

what I wanted to to:

```kotlin
val myMap : ArrayMap<String, Label>
myMap = ArrayMap()
myMap["one"] = new Label(...)
```

But there is no Set operator defined. Am I doing something wrong, or isn't it just implemented yet?

Cheers

**Comment by jcornaz** [comment]
You have to create an extension function for it:

```kotlin
operator fun <K, V> ArrayMap<K, V>.set(key: K, value: V) {
  put(key, value)
}
```

Eventually it could be added to `ktx`...

**Comment by gembutterfly** [comment]
yeah, hoped it's already been there - thank you :)

**Comment by gembutterfly** [comment]
Yeah, but it had been said, that the libgdx implementations are more efficient and use less storage. Nevermind, I did what you explained and extended it myself. Thank you.

**Comment by czyzby** [comment]
@gembutterfly  FYI, from the documentation:

> An ordered or unordered map of objects. This implementation uses arrays to store the keys and values, which means #getKey(Object, boolean) do a comparison for each key in the map. This is slower than a typical hash map implementation, but may be acceptable for small maps and has the benefits that keys and values can be accessed by index, which makes iteration fast.

`ArrayMap` is rarely a good choice, since it loses the main advantage of a hash map. If garbage collection is an issue and you want to rely on LibGDX collections, you should use `ObjectMap` instead.

I still think we could add some basic utility methods for `ArrayMap`, but it's a rather niche collection.

**Comment by woneryf** [comment]
> yeah, hoped it's already been there - thank you :)

wangtest

**Comment by xiaofeixia6666** [comment]
1111111111111111111111111111111111111111111111112222222222222

**Comment by xiaofeixia6666** [comment]
222222222222222222222222222222222333333333333333333333333444444444444444
[yyy.txt](https://github.com/libktx/ktx/files/4000145/yyy.txt)

**Comment by xiaofeixia6666** [comment]
1111111111111111111111111111111111111111111133333333333333333333333333

**Comment by xiaofeixia6666** [comment]
11111111111111111111111111111111122222222222222222222222222

**Comment by xiaofeixia6666** [comment]
33333333333333333333344444444444444444444444444
[yyy.txt](https://github.com/libktx/ktx/files/4000149/yyy.txt)

**Comment by xiaofeixia6666** [comment]
2222222222222222222222222222222222222222222222

**Comment by czyzby** [comment]
Removed some spam.
