### ISSUE TITLE
Migrate to Gradle Kotlin scripting

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#18]
- [ ] Rewrite the main `build.gradle` file to Kotlin.
- [ ] Update `build.gradle` files of subprojects.

_Because we can._

(Low priority.)

**Comment by czyzby** [comment]
https://guides.gradle.org/building-kotlin-jvm-libraries/

**Comment by czyzby** [comment]
These are my thoughts every time I try out Kotlin Gradle scripting. It might be fine for simple projects without many plugins, but I find Groovy configuration more concise and readable for more complex setups for now. About the publishing code - I think it could be greatly simplified even in the current version, but I just don't find it a big priority to refactor when there are actual KTX features and examples to be written. ;)

Thanks for trying this out, by the way.

**Comment by aouerfelli** [comment]
Yeah that's pretty much my opinion as well, thanks for sharing.

As for the publishing code, I couldn't find a better way due to [this] (
https://github.com/gradle/kotlin-dsl/issues/47). It's a pretty old issue,
but I don't think they have a better implementation yet.

**Comment by czyzby** [comment]
I'll go ahead and remove the label, since this issue has a very low priority. Thanks for your contribution, we'll definitely use that if we ever migrate to pure Kotlin Gradle scripts.

**Comment by czyzby** [comment]
@Megamiun ended up migrating our scripts to Kotlin. Thanks for your contribution!

I'd also like to thank @aouerfelli for assessing the Kotlin scripting while it still wasn't very stable. Thanks for your work on this, guys.
