### ISSUE TITLE
Default parameter value for Skin.get

### ISSUE THREAD

**Issue by maltaisn** [libktx/ktx#188]
The skin module has an extension method to get an asset by name, with reified type.
```kotlin
val style = skin.get<ImageButtonStyle>("custom-style")
```
When using the "default" named asset, we have two choices:
```kotlin
val style = skin.get<ImageButtonStyle>("default")
val style: ImageButtonStyle = skin.get(ImageButtonStyle::class.java)
```
Ideally `Skin.get` would have a default value of `"default"` for the name parameter, allowing:
```kotlin
val style = skin.get<ImageButtonStyle>()
```
Can this be added?

**Comment by czyzby** [comment]
Sure, it makes sense.

**Comment by czyzby** [comment]
Thanks @maltaisn.
