### ISSUE TITLE
Json extensions module

### ISSUE THREAD

**Issue by maltaisn** [libktx/ktx#192]
I just began using the `Json` class in my project for saving the game state. I'm mostly using custom serializers instead of reflection for reading and writing. There's a lot of boilerplate that could be avoided with reified extension functions. Here's a few that would be possible:

```kotlin
inline fun <reified T> Json.setSerializer(serializer: Json.Serializer<T>) =
    setSerializer(T::class.java, serializer)

inline fun <reified T> Json.readValue(name: String, jsonData: JsonValue): T =
    readValue(name, T::class.java, jsonData)

inline fun <reified T : Iterable<E>, reified E> Json.readArrayValue(name: String, jsonData: JsonValue): T =
    readValue(name, T::class.java, E::class.java, jsonData)
```
And a comparison with actual methods:
```kotlin
fun main() {
  val json = Json()

  // Without extension
  json.setSerializer(Vector2::class.java, object : Json.Serializer<Vector2> { /* ... */ })

  // With extension
  json.setSerializer(object : Json.Serializer<Vector2> { /* ... */ })
}

class World : Json.Serializable {

  var startTime = System.currentTimeMillis()
  var playerPos = Vector2()
  var coinsPos = mutableListOf<Vector2>()

  override fun write(json: Json) {
    json.writeValue("startTime", startTime)
    json.writeValue("playerPos", playerPos)
    json.writeValue("coinsPos", coinsPos)
  }

  override fun read(json: Json, jsonData: JsonValue) {
    // Without extensions
    playerPos = json.readValue("playerPos", Vector2::class.java, jsonData)
    startTime = jsonData.getLong("startTime")
    @Suppress("UNCHECKED_CAST")
    coinsPos = json.readValue("coinsPos", ArrayList::class.java, Vector2::class.java, jsonData) as MutableList<Vector2>

    // With extensions
    startTime = jsonData.getLong("startTime")  // No changes
    playerPos = json.readValue("playerPos", jsonData)  // Value type inferred
    coinsPos = json.readArrayValue("coinsPos", jsonData)  // Collection and elements types inferred, no cast
  }
}
```
These functions would allow type inference when reading values. It would also improve type safety when reading Json arrays when arrays contain value types with custom serializers, Vector2 in this case.

**Comment by czyzby** [comment]
There's already a ton of JVM JSON serializers, some of them written specifically for Kotlin, and a lot of them more performant and feature-complete. If you feel like the original LibGDX JSON serialization is lacking, you might want to give them a try.

To be honest, I think including a custom JSON serialization implementation in LibGDX might have been a mistake in the first place. Maintaining a custom serialization lib - or even extensions to the current one - would be a lot of work for little benefit.

**Comment by czyzby** [comment]
That being said, if you've already written the extensions or would like to contribute, I could review the PR. Give something like `kotlinx.serialization` a chance before though to see if conforming to LibGDX API is even worth it.

**Comment by maltaisn** [comment]
I decided to use libGDX's json since Skin already use it and I didn't want to include two different json serialization libraries in my game.

But looking at kotlinx.serialization I realize that it's probably a better option anyway, so I won't make a pull request.

As you said, LibGDX JSON serialization looks like a mistake. It should probably have been made private.

**Comment by czyzby** [comment]
> I decided to use LibGDX's JSON since Skin already use it and I didn't want to include two different json serialization libraries in my game.

That's a valid reason for using LibGDX serialization. If it works and you already have the utilities written, don't worry too much about switching. Although keep in mind that it accepts invalid JSONs and is likely untested (other than in production by fellow devs).

Anyway, they should have just went with some popular Java choice that supports multiple platforms and add GWT support for it instead of creating a custom module. This is a common problem with LibGDX though. (Don't get me started on their collections.)

**Comment by maltaisn** [comment]
Actually I decided to keep using LibGDX JSON. I feel like my game classes are too simple to justify using something like Gson and use too much inheritance to work well with kotlinx.serialization. And as I said earlier, I don't want to include two libraries for the same thing.

So if you're still interested with a pull request I can make it.

**Comment by czyzby** [comment]
Sure, I'll take a look.

**Comment by czyzby** [comment]
I'm not a fan of the LibGDX JSON API and I might have overreacted by closing this issue. Seeing these utilities in the PR made me realize this would be very useful when you're forced to work with existing codebase with LibGDX serialization. I still recommend anyone to look into popular serialization libraries when writing stuff from scratch, but I can see the value in improving this part of the LibGDX API.

**Comment by czyzby** [comment]
Thanks for the contribution @maltaisn, feel free to open additional issues if you think `ktx-json` could improve LibGDX's `Json` further.

**Comment by czyzby** [comment]
Reopening, as the API could be improved. Avoid weird parameter order, use default params for overloaded methods.

**Comment by czyzby** [comment]
Thanks @maltaisn.
