### ISSUE TITLE
NoClassDefFoundError on iOS when using `then`

### ISSUE THREAD

**Issue by thebnich** [libktx/ktx#204]
I'm getting a rather obscure error on iOS when using `then` (e.g., `Actions.alphaTo(1f) then Actions.alphaTo(1f)`):

```
java.lang.NoClassDefFoundError: java.util.function.Consumer
	at java.lang.VMClassLoader.findClassInClasspathForLoader(Native Method)
	at java.lang.PathClassLoader.findClass(PathClassLoader.java:193)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:515)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:475)
	at ktx.actors.ActionsKt.addUnwrapped(actions.kt:52)
	at ktx.actors.ActionsKt.then(actions.kt:45)
```

As a workaround, changing to `Actions.sequence()` works with no issues.

KTX: 1.9.9-b2
libGDX: 1.9.10
Kotlin: 1.3.41
RoboVM: 2.3.7

**Comment by czyzby** [comment]
What's your source compatibility level? It looks like Kotlin tries to compile against Java 8. Try adding these in `build.gradle`:

```groovy
sourceCompatibility = 1.6
targetCompatibility = 1.6

compileKotlin {
    kotlinOptions {
        jvmTarget = "1.6"
    }
}
```

**Comment by thebnich** [comment]
Hm, adding that to both my iOS and core `build.gradle` files made no difference (`sourceCompatibility` was previously set to 1.7 in each).

**Comment by czyzby** [comment]
We might have to add the `jvmTarget` in our build files. I'll publish a snapshot release this weekend with the changes on our side (and LibGDX 1.9.10 compatibility) and let you know, I'd appreciate if you take a look.

**Comment by czyzby** [comment]
I updated the JVM target and uploaded KTX `1.9.10-SNAPSHOT`. You can use it by adding this repository in your `build.gradle`: 

```groovy
maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
```

Let me know if that fixed your issue.

**Comment by czyzby** [comment]
(Build failed due to JDK installation issues, unrelated to Kotlin JVM target.)

**Comment by thebnich** [comment]
Yep, that did the trick. Thanks!

**Comment by czyzby** [comment]
Thanks for testing, I'll release `1.9.10-b1` with the fix this weekend.

**Comment by czyzby** [comment]
@thebnich Just wanted you to know that `1.9.10-b1` should be available shortly. It's pretty much the same in terms of content as the snapshot you're currently using, but you might want to move to the stable version, as `1.9.10-SNAPSHOT` can be overridden and contain new API changes.
