### ISSUE TITLE
Box2D shapes are not getting disposed?

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#208]
I don't know if this is an issue or if it is intended but according to the box2d libktx documentation you can create a body like this.

```kotlin
world.body(BodyDef.BodyType.StaticBody) {
    position.set(16f, 1f)
    box(width = 30f, height = 1f)
}
```
However, shouldn't the shape's dispose method be called after creating the fixture? I don't see that happening but maybe I am blind.
Or should that be done manually by the user? What would be the most elegant way to do that?

**Comment by czyzby** [comment]
You are right, this is a potential memory leak. We'll add an option to dispose the shape after fixture creation that can be turned off if you want to reuse some custom shapes for multiple fixtures.

**Comment by czyzby** [comment]
Thanks, I've pushed a fix to `develop`. Snapshot release will be available shortly.

**Comment by Quillraven** [comment]
Thanks a lot for the quick fix!
