### ISSUE TITLE
Add SpriteBatch extension function for using a projection matrix

### ISSUE THREAD

**Issue by jakewilson** [libktx/ktx#214]
Hello, I use artemis-odb for my ECS so I'm unable to utilize the awesome `batch.use {...}` extension because each entity that is rendered is a separate function call. Instead I call `batch.begin()` and `batch.end()` in my system's `begin()` and `end()` functions. It's not a huge deal, but I'd like to be able to call `batch.begin(projectionMatrix = camera.combined)`. If this is something ktx is interested in, I would be more than happy to add this functionality myself.

Thanks!

**Comment by czyzby** [comment]
This is a valid use case and contributions are always welcome. If you'd like to add this functionality, you can create two extension functions: one with a `projectionMatrix` parameter and one with a `camera` (that would automatically extract `camera.combined`). This is similarly to how we handle it in `use`.

**Comment by jakewilson** [comment]
Cool, I'll get started!

**Comment by czyzby** [comment]
Thanks for the contribution @jakewilson!
