### ISSUE TITLE
Adapters for Json.Serializer and Json.ReadOnlySerializer

### ISSUE THREAD

**Issue by rhutsaliuk** [libktx/ktx#217]
I've noticed couple of things which could be a bit more kotlin-friendly when writing custom serializer.
IDEA auto-implements all serializer paramters nullabe. And the `knownType`  and `type` are of type `Class<*>?`. So, the auto-implemented serializer looks like this:
```kotlin
class MySerializer: Json.Serializer<MyClass> {
  override fun write(json: Json?, `object`: MyClass?, knownType: Class<*>?) {
  }

  override fun read(json: Json?, jsonData: JsonValue?, type: Class<*>?): MyClass {
  }
}
```
I analyzed the sources of `com.badlogic.gdx.utils.Json` and noticed that only the last parameter of both methods may be `null`. In all the other cases the serializer is simply not called, so that we can omit `?`. Additionally the `object` parameter could be renamed to something that does not reqire quotes. And `Class<*>?` could be converted to `KClass<*>?` (this one requires new method). Basically the adapter may look like this:
```kotlin
abstract class KtxSerializer<T> : Json.Serializer<T> {
  final override fun write(json: Json, obj: T, knownType: Class<*>?) {
    // the same for the read method
    write(json, obj, knownType?.kotlin)
  }
  abstract fun write(json: Json, obj: T, knownType: KClass<*>?)
}
```
And the same can be done for `com.badlogic.gdx.utils.Json.ReadOnlySerializer`.
But generally I think it does not make much sense if not the `Class<*>`, as we could simply omit the question marks and rename the parameter. But if changing the type of the `type` and `knownType` parameters then why not do the others.
So, if that all makes sense, I can submit a PR. Though I'm not sure what to test here except the parameters that are passed to new methods (including conversion of `Class` to `KClass`).

**Comment by rhutsaliuk** [comment]
Well, as it's sunday evening and I have nothing to do :smiley:, I can already submit the PR if this feature is relevant.

**Comment by czyzby** [comment]
We've done something similar in `ktx-app` module, so we could improve LibGDX typing, although this might be more beneficial to add `@NonNull`/`@Nullable` annotations in LibGDX codebase.

Correct me if I'm wrong, as I haven't checked the sources yet, but is `Json.Serializer` something like a single function interface? Maybe we could choose a more Kotlin-like approach and instead of providing a class, we might add an (inlined) factory function, e.g.:

```kotlin
val mySerializer: Json.Serializer<Thing> = jsonSerializer<Thing> { json, obj, type ->
  // Your serialization code.
}
```

**Comment by rhutsaliuk** [comment]
No, it's an interface with two functions `read` and `write`. Here is the exact code from libgdx sources:
```java
static public interface Serializer<T> {
  public void write (Json json, T object, Class knownType);
  public T read (Json json, JsonValue jsonData, Class type);
}
```
And the `Json` object does not distingush serializers that are able to only read or only write. So, it won't be possible to write a function that creates a serializer  with only `read` or only `write` implementation, because `Json` maps serializer to a `Class` object, so we simply can't set two serializers for single class.

**Comment by czyzby** [comment]
Well, you can have 2 lambda parameters, but I guess you're right that it would be less readable.

I'm pretty sure you can do `abstract override fun` on Java functions with `!` types to specify the typing, you can check if you need to declare 2 function for write/read or if you can just define 2 abstract functions with the correct typing.

**Comment by rhutsaliuk** [comment]
If I undestand you right, yes the `!` types will work for sure. The main difference is the third parameter, in both methods: `Class<*>`. This is something that I'm not really sure and hope you may know.
If in any case it is not helpfull to have `KClass<*>` instead of `Class<*>`, then we can just close this issue.

**Comment by czyzby** [comment]
We could improve the typing regardless of `KClass` usage with an abstract class with "overridden" abstract methods. I think both are relatively easy to convert to one another.

What's your use case for having a `KClass` parameter instead of `Class`?

**Comment by czyzby** [comment]
I think something like this would still be useful without introducing new methods:

```kotlin
 interface JsonSerializer<T>: Json.Serializer<T> {
   override fun read(json: Json, jsonValue: JsonValue, type: Class<*>?): T
   override fun write(json: Json, value: T, type: Class<*>?)
 }
```

**Comment by rhutsaliuk** [comment]
> What's your use case for having a `KClass` parameter instead of `Class`? I think both are relatively easy to convert to one another.

Well, my case was simply to make it more kotlin-oriented. But I start thinking that it does not really worth it. 
And your option with interface looks cool. I didn't realize kotlin supports overriding interface methods.
We probably can make use of that.

**Comment by czyzby** [comment]
Great, would you like to update your branch and submit the PR?

**Comment by rhutsaliuk** [comment]
Yes, sure. I'll do that

**Comment by rhutsaliuk** [comment]
Oh, and I forgot also. In addition to `Json.Serializer` libgdx provides a `Json.ReadOnlySerializer` which is a [class](https://github.com/libgdx/libgdx/blob/master/gdx/src/com/badlogic/gdx/utils/Json.java#L1209) simply implementing `Json.Serializer`, with no-op `write` method.
We could have a kotlin alternative with the overriden interface methods to do the same, like this:
```kotlin
interface ReadOnlySerializer<T> : Json.Serializer<T> {
  override fun write(json: Json, obj: T, knownType: Class<*>?) = Unit
  override fun read(json: Json, jsonData: JsonValue, type: Class<*>?): T
}
```
 Plus we can introduce couple of functions that could use lambda for creation of read-only serializers, like this: 
```kotlin
inline fun <reified T, F> readOnlySerializer(read: F): Json.Serializer<T>
    where F : (Json, JsonValue) -> T {
  return object : ReadOnlySerializer<T> {
    override fun read(json: Json, jsonData: JsonValue, type: Class<*>?): T = read(json, jsonData)
  }
}
```
Does that make sense as an alternative for `Json.ReadOnlySerializer` ?

**Comment by czyzby** [comment]
Sure, sounds like a nice feature.

You typically use `where` if you need to define multiple upper bounds for a generic parameter, e.g. if you need it to implement multiple interfaces. To make this easier to use, the function should have only a single reified generic parameter of `T`. I'd refactor it somewhat like this:

```kotlin
inline fun <reified T> readOnlySerializer(crossinline read: (Json, JsonValue) -> T): Json.Serializer<T> 
  = object : ReadOnlySerializer<T>() {
    override fun read(json: Json, jsonValue: JsonValue, type: Class<*>?): T = read(json, jsonValue)
  }
```

**Comment by rhutsaliuk** [comment]
Yeah, you right. I'll do without the `where`. Thanks for the advice.

**Comment by czyzby** [comment]
Thanks again for your contribution. A snapshot release with your changes should be available soon.
