### ISSUE TITLE
AssetContainer

### ISSUE THREAD

**Issue by cypherdare** [libktx/ktx#222]
This is an idea for utilizing the asset delegate classes to easily manage groups of assets with minimal typing. I used a similar concept for CoveTools' [AssignmentAssetManager](https://github.com/CypherCove/CoveTools#assignmentassetmanager), but the usage of that is ugly in Kotlin due to null-safety, and I think this could be more feature rich.

Usage would be to subclass AssetContainer to define groups of assets by delegate so they could easily be loaded and unloaded. Here are some examples.

**Complex game with groups of assets for different screens:**
```kotlin
// Define some containers like this:
class PauseScreenAssets: AssetContainer(
        assetManager, 
        pathPrefix = "pause/"){
    val skin by delayedAsset<Skin>("mySkin.json")
    val music by delayedAsset<Music>("pauseMusic.ogg")
    //...
}

// Load and unload whole containers:
fun goToMapScreen(){
    stage1Assets.unloadAll()
    with(mapAssets) {
        loadAll()
        finishLoading()
    }
    //...
}
```

**Simple game where all assets are loaded at once:**
We can almost do this already, but it's a little easier to read through the list of assets when they don't all have `assetManager.load` written before them.
All the assets can be defined in a single file, and a default built-in AssetManager can be used so the whole thing is wrapped to a simpler object that lists all the Textures, Sounds, Shaders, etc.
```kotlin
class Assets: AssetsContainer() {
    val atlas by asset<TextureAtlas>("myAtlas")
    val logo by asset<Texture>("logo.png")
    //...

    override fun onLoadingFinished() {
        // Here's a hook for acquiring AtlasRegion references, etc.
    }
}
```

**Work with specific Asset objects even though they were used as delegates (requires reflection):**
```kotlin
// Within the AssetContainer subclass:
::myTexture.toAsset().unload()

// Outside the class:
myAssetContainer.getAsset{::myTexture}.unload()
```

Here's how I've outlined a prototype. If this kind of detailed helper class is a good fit for KTX, we can discuss improving on this and making it more elegant. (Not sure if it's in KTX's scope to go this far with a helper class.)

```kotlin
open class AssetContainer(val assetManager: AssetManager = AssetManager(),
                          val filePrefix: String = ""): Disposable {
    private val assets = com.badlogic.gdx.utils.Array<Asset<*>>()

    fun add(asset: Asset<*>) = assets.add(asset)

    fun remove(asset: Asset<*>) = assets.removeValue(asset, true)

    fun loadAll() {
        for (asset in assets)
            asset.load()
    }

    fun unloadAll() {
        for (asset in assets)
            asset.unload()
    }

    fun isLoaded(): Boolean = assets.all { it.isLoaded() }

    fun update(): Boolean =
            assetManager.update().also {
                if (isLoaded())
                    onLoadingFinished()
            }

    fun finishLoading() {
        assetManager.finishLoading()
        onLoadingFinished()
    }

    /** Perform actions in response to the AssetManager finishing loading of all assets in this container.
     * Called automatically if the loading is completed by calling this class's [update] or [finishLoading].
     */
    open fun onLoadingFinished() {}

    // Requires reflection
    fun <T> KProperty0<T>.toAsset(): Asset<*> {
        val delegate = getDelegate()
        require(delegate is Asset<*>) { "The property must be a member of this class and use an Asset delegate." }
        return delegate
    }

    /** Creates an asset, queues it for loading, and adds it to the container. */
    protected inline fun <reified T : Any> asset(fileName: String, params: AssetLoaderParameters<T>? = null) =
            assetManager.load("$filePrefix$fileName", params).also { add(it) }

    /** Creates an asset and adds it to the container. It will be loaded on demand. */
    protected inline fun <reified T : Any> delayedAsset(fileName: String, params: AssetLoaderParameters<T>? = null) =
            assetManager.loadOnDemand("$filePrefix$fileName", params).also { add(it) }

    /** Disposes the associated [AssetManager]. Do not use if the asset manager is also used externatlly.
     * Use [unloadAll] instead.
     */
    override fun dispose() {
        assetManager.dispose()
    }
}

// Requires reflection
inline fun <T: AssetContainer> T.getAsset(assetProperty: T.() -> KProperty0<*>): Asset<*> =
    assetProperty().toAsset()
```

**Comment by czyzby** [comment]
`AssetContainer` name, although appropriate, was already used for a coroutine-based `AssetManager` alternative. Maybe `AssetBundle` or `AssetGroup` makes sense?

Not sure about reflection usage and associated functions. Direct access to the asset wrapper seems like a rare use case; you could assign it directly to the property with using `by` delegate to get a similar effect if needed.

`onLoadingFinished` seems error-prone in its current state. It could fire multiple times when used inappropriately, or not at all if `AssetManager` is updated externally. Unless you can find a way to implement a reliable asset loading listener, I don't think we should provide this functionality.

`dispose` should dispose of the associated assets, not the entire manager. I also wouldn't provide a default value for the `AssetManager` in constructor to encourage reusing of the assets and maintaining a single manager.

I think it's a neat idea, but we could focus on the most common use cases (grouping asset and mass actions such as loading/disposing) and simplify the API. Would you like to submit a PR?

**Comment by cypherdare** [comment]
I like `AssetGroup`. It avoids the naming incongruity of having an AssetBundle that references I18NBundles.

Stepping back, yes, I agree about taking out the reflection. If someone wants to micromanage individual assets from the group, all that's needed is to use `= asset()` instead of `by asset()`. Also, it removes the awkwardness of wondering how assets that are externally added with `add` would be managed.

I agree with `dispose` only unloading the assets of the group. That way there's no risk of messing up other groups that share the same manager. 

If we take out the default AssetManager, it's still easy to just put one in the super-constructor call in the subclass. And if you're using it in the monolithic assets class way in my second example above, then you'd still be disposing everything that needs to be disposed by unloading everything.

I'm thinking of removing `onLoadingFinished()` and just making `update()` and `finishLoading()` open so people can create hooks that way if they want to. The problem with `onLoadingFinished()` is that it won't be called if the asset manager is called to finish loading by direct calls, not through the container calls. That creates a mess if two groups are queued for loading at once.

I think it would be good if `add` did a check like this:
```
fun add(asset: Asset<*>) {
    require(asset.manager == manager) { "The asset must use the same manager as this group." )      
    assets.add(asset)
}
```
This would require making `manager` a property of the Asset interface so both DelayedAsset and Managed asset can be checked. This is potentially breaking if someone has made their own Asset implementation (though maybe that's unlikely). The property could be nullable to keep Asset versatile. Thoughts?

I'll prepare a PR.

**Comment by cypherdare** [comment]
I'm debating whether pass-through functions like `add()`, `addAll()`, `remove()`, `removeAll()`, and `contains()` should be here. It allows the AssetGroup class to be used without subclassing, but at that point it's hardly better than using a Set directly. Not sure there would be a point.

Also, if it does have `contains()`, I think ManagedAsset and DelayedAsset would need proper `equals` and `hashCode` functions (potentially a breaking change, but low risk).

But `equals` for an Asset is hardly helpful, since AssetDescriptor doesn't have a defined `equals` either. It's sort of ambiguous because AssetManager treats any two Assets with the same file name as equivalent, even if they have different `params`. I think this is a shortcoming of AssetManager because you might possibly want to load two copies of a file with different parameters, like multiple shaders using different appended preprocessor code. [On a side note, maybe it could be fixed by configuring them to be stored by an Object key, which by default is the file name if no key was explicitly provided. But AssetManager is a beast of a class. Not sure I want to touch that.]

So anyway, I'm leaning toward making this class abstract, and exclusively used by defining assets via member properties. Perhaps the one thing we could do here that actually would be helpful is make this class Iterable, so you could do some custom stuff with all assets of a certain type, or loading status, etc. If we do that, maybe `val assetDescriptor` should be moved up to Asset so the asset type can be accessed from any Asset<*>.

**Comment by czyzby** [comment]
`abstract class` sounds good. Comparing assets is tricky, as you've noticed. I'd avoid turning `AssetGroup` into a collection and instead create a minimum viable API for the most common use case: mass actions for certain groups of assets. Seems like `load`/`dispose` is all you need.

**Comment by cypherdare** [comment]
I've run into a detail that needs some discussion. It has to do with the reference counting behavior of AssetManager.

An asset only gets reference counted by AssetManager when it completes loading. So this:
    `repeat(10) { manager.load(myAssetDescriptor) }.also { manager.finishLoading() }`
produces a single reference count of an asset. If you call `manager.unload(myAssetDescriptor)`, the ref count goes to zero so it is disposed. But if you call this:
```
repeat(10) {
    manager.load(myAssetDescriptor)
    manager.finishLoading()
}
```
Now it has a reference count of 10, so you would have to unload the asset 10 times to get it to be disposed.

ManagedAsset and DelayedAsset don't make this inherently any more risky than it already is. But I think AssetGroup currently does make it more risky since it allows the individual Assets of the AssetGroup to be accessed if they weren't used as delegates. Allowing this sort of encourages the user to take actions that will cause issues. Someone might load a specific group member, later `loadAll`, and then call `dispose()`, expecting all the assets to be released. But one of the assets will still have an extra reference count and still be alive.

At least as it is, a good general contract for using AssetManager would be to not load an asset from multiple places and clean it up from multiple places--the reference counting is really only good for handling dependencies. I don't think we want to encourage use that violates this contract.

I think the best option here is to create a separate AssetGroupMember delegate that doesn't implement Asset and doesn't provide `load` and `unload` calls. This simplifies the whole usage of AssetGroup by stripping out any micro-management functionality. Calling `load` or `dispose` on the AssetGroup will increment or decrement the reference counts of all members by one each time.

Other alternatives are to not worry about it and allow users to micromanage (just give them a warning about the behavior in the docs), or to subclass or modify DelayedAsset so it keeps an internal load/unload call count. I don't like either of these options.

**Comment by cypherdare** [comment]
Here's my current version:

```Kotlin
/**
 * A class for managing a group of assets together, such that they can be loaded or unloaded en masse.
 * [AssetGroup] should be subclassed and the assets should be defined by properties in the subclass by using [asset] as
 * a delegate. The group of assets will not be queued for loading with the [AssetManager] until [load] is called.
 * Accessing any of the asset properties that were defined with this delegate will block until the [AssetManager] is
 * finished loading. Accessing any of the asset properties before the group has been queued for loading is not allowed
 * and will throw an exception (this limitation enables non-nullable asset properties).
 * @param manager The [AssetManager] that will handle loading and unloading of this group.
 * @param filePrefix A string that will be prefixed to any file path parameter passed to [asset].
 */
abstract class AssetGroup(val manager: AssetManager, protected val filePrefix: String = "") : Disposable {
  inner class Member<Type>(val assetDescriptor: AssetDescriptor<Type>) {
    operator fun getValue(thisRef: AssetGroup, property: KProperty<*>): Type {
      if (!isLoaded()) {
        manager.finishLoading()
        if (!manager.isLoaded(assetDescriptor.fileName))
          error("AssetGroup members cannot be accessed before the group has been queued for loading with load()." )
      }
      return manager[assetDescriptor]
    }
  }

  /** The backing set containing the assets of this group. There is no need to manually add assets to this set if using
   * [asset].
   */
  protected val members = com.badlogic.gdx.utils.ObjectSet<Member<*>>()

  /** Queues all assets of this group for loading by the associated [AssetManager]. */
  fun load() {
    for (member in members)
      manager.load(member.assetDescriptor)
  }

  /** Unloads all of the assets in this group. If any of the assets are dependencies of assets outside this group,
   * the associated [AssetManager] will retain them. */
  fun unload() {
    for (member in members)
      manager.unload(member.assetDescriptor.fileName)
  }

  /** Unloads all of the assets in this group, ignoring any thrown exceptions. If any of the assets are dependencies of
   * assets outside this group, the associated [AssetManager] will retain them. */
  fun unloadSafely() {
    try {
      unload()
    } catch (exception: Exception) {
      exception.ignore()
    }
  }

  /** @see [unload] */
  override fun dispose() = unload()

  /** @return true if all of the assets in this group are finished being loaded by the associated [AssetManager]. */
  fun isLoaded(): Boolean = members.all { manager.isLoaded(it.assetDescriptor) }

  /** Creates a delegate for an asset and registers it as a member of this group.
   * @param fileName Name of the file used to reference this asset by the AssetManager. This value will be prefixed with
   * [filePrefix].
   * @param params optional asset loading parameters which might affect how the assets are loaded. Can be null.
   * @return a delegate for an asset, registered as a member of this AssetGroup.
   * */
  protected inline fun <reified T : Any> asset(fileName: String, params: AssetLoaderParameters<T>? = null) =
      Member(assetDescriptor("$filePrefix$fileName", params)).also { members.add(it) }
}
```

**Comment by czyzby** [comment]
Invalid reference counting seems like a bug in LibGDX, unless I'm misunderstanding something.

* Not sure about the `Member` - it's a bit of a duplication with less flexibility. I think the inner delegate might be a bit excessive and using `Asset` is OK, as long as the documentation warns about possible risks of accessing it directly. Current API would basically work against someone who knows the risks and needs more control over some assets in the groups. And calling `finishLoading` on `getValu` is risky, as it blocks until all assets are loaded AFAIK.
* `update` method might also be useful. It would return `true` not when the `AssetManager` has finished loading, but when `isLoaded()` returns `true`. Basically `manager.update(); return isLoaded()`.

**Comment by cypherdare** [comment]
I modeled Member after DelayedAsset, and it does the same thing, blocking until all assets are loaded if you try to access it. I don't know the original reason for this behavior, but I figure it's a safe way to make it usable for a non-nullable delegate. ManagedAsset will instead throw an Exception (indirectly from AssetManager) when an unloaded property is accessed.

I think I'll go back to providing ways to use either ManagedAsset or DelayedAsset, so you have the flexibility to decide whether you want your assets preloaded with the manager at group instantiation. The methods for them could either be respectively `asset/delayedAsset` or `preloadedAsset/asset` depending on what we think is the more likely use case.

ManagedAssets are a good fit for someone that instantiates groups when it's time to use them and disposes/null-out when finished with them. Also a good option for a project with a single monolithic AssetGroup that is only ever assigned to a non-nullable reference. Or a project that passes the AssetManager reference around and lets individual Screens (or similar submodules) instantiate their own groups.

DelayedAssets are a good fit for someone that carries many group references in one class and wants them all non-nullable.

I suppose the ManagedAsset way fits more uses cases I can think of. However, if someone uses it and then calls `loadAll()` on the group, now it will take two `unloadAll()` calls to actually dispose of the group. Very easy and silent error to make. That might be a reason to provide DelayedAsset exclusively.

I will add a note saying it's not advised to use `loadAll` or `unloadAll` if selectively loading members of the group. I can't simply have `loadAll` choose to load only the unloaded members, because some of them may be dependencies of other assets.

I think I'll remove `Disposable`. If someone is managing the items individually, `dispose` for the whole group becomes ambiguous. And since the AssetManager is the true Disposable, and it is passed into the constructor, that would add another layer of ambiguity. I know many individual assets are `Disposable`s, but they aren't supposed to be directly disposed if they were loaded by an AssetManager because it messes up reference counting--so, having Disposable member references is not a good justification for the group implementing Disposable.

Here's the latest:
```Kotlin
/**
 * A class for managing a group of assets together, such that they can be loaded or unloaded en masse.
 * [AssetGroup] should be subclassed and the assets should be defined by properties in the subclass by using [asset] or,
 * [delayedAsset] which can be used as delegates.
 * If the asset properties reference [Assets][Asset] instead of using delegates, it is possible to selectively load and
 * unload them. In this case, it is not advised to use [loadAll] and [unloadAll], because AssetManager's reference
 * counts will be thrown off.
 * @param manager The [AssetManager] that will handle loading and unloading of this group.
 * @param filePrefix A string that will be prefixed to any file path parameter passed to [asset].
 */
abstract class AssetGroup(val manager: AssetManager, protected val filePrefix: String = "") {
  /** The backing set containing the assets of this group. There is no need to manually add assets to this set if using
   * [asset] or [delayedAsset]. */
  protected val members = com.badlogic.gdx.utils.ObjectSet<Asset<*>>()

  /** Queues all assets of this group for loading by the associated [AssetManager].
   * If a subset of assets of this group are already loaded, their load counts in the AssetManager will still be
   * incremented. */
  fun loadAll() {
    for (member in members)
      member.load()
  }

  /** Unloads all of the assets in this group. If any of the assets are dependencies of assets outside this group, or if
   * they were loaded more than once, their load counts will only be decremented by one and the associated [AssetManager]
   * will retain them. */
  fun unloadAll() {
    for (member in members)
      member.unload()
  }

  /** Unloads all of the assets in this group, ignoring any thrown exceptions. If any of the assets are dependencies of
   * assets outside this group, or if they were loaded more than once, their load counts will only be decremented by one
   * and the associated [AssetManager] will retain them. */
  fun unloadAllSafely() {
    try {
      unloadAll()
    } catch (exception: Exception) {
      exception.ignore()
    }
  }

  /** @return true if all of the assets in this group are finished being loaded by the associated [AssetManager]. */
  fun isLoaded(): Boolean = members.all { it.isLoaded() }

  /** Creates a delegate for an asset, queues it for loading, and registers it as a member of this group.
   * @param fileName Name of the file used to reference this asset by the AssetManager. This value will be prefixed with
   * [filePrefix].
   * @param params optional asset loading parameters which might affect how the assets are loaded. Can be null.
   * @return an [Asset], registered as a member of this AssetGroup.
   * */
  protected inline fun <reified T : Any> asset(fileName: String, params: AssetLoaderParameters<T>? = null) =
      manager.load("$filePrefix$fileName", params).also { members.add(it) }

  /** Creates a delegate for an asset and registers it as a member of this group.
   * @param fileName Name of the file used to reference this asset by the AssetManager. This value will be prefixed with
   * [filePrefix].
   * @param params optional asset loading parameters which might affect how the assets are loaded. Can be null.
   * @return an [Asset], registered as a member of this AssetGroup.
   * */
  protected inline fun <reified T : Any> delayedAsset(fileName: String, params: AssetLoaderParameters<T>? = null) =
      manager.loadOnDemand("$filePrefix$fileName", params).also { members.add(it) }
}
```

**Comment by czyzby** [comment]
> I modeled Member after DelayedAsset, and it does the same thing, blocking until all assets are loaded if you try to access it.

Because, unfortunately, this happens to be the only way to wait for an asset to be loaded. Still, I don't think this should be the default behavior, so separating it into 2 methods seems like a good idea.

`asset` and `delayedAsset` should explain practical differences between the two in their docs.

You can also add `unload` variant with a lambda that consumes an exception, so that each disposing failure can be handled individually. See `Disposable` utilities.

**Comment by czyzby** [comment]
Thanks again for the contribution, your changes are being uploaded in the latest snapshot as I'm writing this comment.
