### ISSUE TITLE
Inline classes for common color formats

### ISSUE THREAD

**Issue by cypherdare** [libktx/ktx#224]
I think it would be nice to have some inline classes for the most common color formats RGB888, RGBA8888, ARGB8888, and ABGR8888. This would allow doing color manipulations and math in loops without GC churn/pooled Colors, and reduced floating point math. It would also allow for working more easily with hexadecimal color integers and converting between them--nice for working with Pixmaps.

Something like this:

```Kotlin
inline class Rgba (val data: Int) {
  /** Interprets the least significant four bytes as RGBA8888. */
  constructor(long: Long): this(long.toInt())
  /** Pass values in the range 0..255. */
  constructor(r: Int, g: Int, b: Int, a: Int) : this((r shl 24) or (g shl 16) or (b shl 8) or a)

  // These would return the components as Ints in the range 0..255
  inline val r get() = data shr 24
  inline val g get() = (data and 0xff0000) shr 16
  inline val b get() = (data and 0xff00) shr 8
  inline val a get() = data and 0xff
  // Could also have rf, gf, bf, and af to return floats in 0..1 range.

  // Modify the individual components using Integers in the range 0..255.
  inline fun withR(newR: Int) = Rgba((newR shl 24) or (data and 0xffffff))
  inline fun withG(newG: Int) = Rgba((newG shl 16) or (data and 0xffff00ff.toInt()))
  inline fun withB(newB: Int) = Rgba((newB shl 8) or (data and 0xffff00ff.toInt()))
  inline fun withA(newA: Int) = Rgba(newA or (data and 0xffffff00.toInt()))
  // Also overloads with floats in 0-1 range

  // These would apply appropriate clamping like the Color class does
  operator fun times(scale: Float) = Rgba(...)
  operator fun div(denom: Float) = Rgba(...)
  operator fun plus(other: Rgba) = Rgba(...)
  operator fun minus(other: Rgba) = Rgba(...)

  inline fun toArgb() = Argb((data shr 8) or (a shl 24))
  inline fun toRgb() = Rgb(data shr 8)
  inline fun toAbgr() = Abgr((a shl 24) or ((data and 0xff00) shl 8) or ((data and 0xff0000) shr 8) or r)
  inline fun toColor() = Color.rgba8888ToColor(Color(), this)
  inline fun toInt() = data
  /** Converts the color to a packed ABGR float (for use in a shader uniform or vertex attribute). 
  * Alpha is compressed to 0-254 to avoid using bits in the NaN range. */
  inline fun toFloatBits() = toAbgr().toFloatBits()

  override fun toString(): String = "RGBA(#${data.toLong().toString(16)})"
}

/** Interprets the integer as RGBA8888. */
fun Int.toRgba() = Rgba(this)
/** Interprets the least significant four bytes as RGBA8888. */
fun Long.toRgba() = Rgba(this) // because 0x70000000 and above are interpreted as longs
/** Converts a packed ABGR float color to RGBA8888. */
fun Float.toRgba() = Abgr(NumberUtils.floatToIntColor(this)).toRgba()

fun Color.set(rgba: Rgba) {...}
fun Color.toRgba() = Rgba(...)

fun Batch.setColor(rgba: Rgba) = Batch.setPackedColor(rgba.toFloat())
```

And so on for the other common color formats.

**Comment by czyzby** [comment]
1) This is unlikely to improve performance of APIs that consume LibGDX `Color` instances - or might even make it worse due to necessary conversions.
2) Supporting extension methods for APIs that traditionally consume `Color` seems like a major effort.

We could merge something like this into `ktx-graphics`, but I think we should run some benchmarks first to see if it has any significant impact. Most games wouldn't really benefit from this by much, I think.

**Comment by cypherdare** [comment]
SpriteBatch stores color as a packed float and has to convert to packed float whenever you call `setColor` instead of `setPackedColor`. I remember someone saying on Discord it made a very  significant benchmarked difference to use `setPackedColor`. So he was storing colors as packed floats in any game entity that wasn't frequenctly changing color. 

Unfortunately, SpriteBatch was recently changed to store the color in both Color and float formats, so the savings doesn't work any more unless you subclass SpriteBatch to not convert the color.

I think the primary benefits don't have to do with GC/pooling, because there typically isn't very much color manipulation to do.

I'll either benchmark this or close it in the near future (if it doesn't look like it's going to be worth the effort).

**Comment by czyzby** [comment]
I see.

> I'll either benchmark this or close it in the near future (if it doesn't look like it's going to be worth the effort).

Thanks, I think that's the correct approach. Since this is not a typical API improvement by itself, we should be sure that it improves performance or memory usage before merging this.

**Comment by cypherdare** [comment]
I put together a [benchmark here](https://github.com/cypherdare/libgdx-color-benchmark). It draws 2000 basic game objects 1000 times each. You can draw them with or without some basic color manipulations, with or without having SpriteBatch back up the color with a Color object (the Color object backup is recently added behavior), and with or without using an inline RGBA color class.

On my PC and on a Google Pixel 1, there is negligible performance difference for any of these cases. It was just barely different in some combos, but I still consider it negligible because you wouldn't be drawing anywhere near 2M objects in a real game.

**Comment by czyzby** [comment]
Thanks for the benchmarks, good job.
