### ISSUE TITLE
In-place functions for GdxArray

### ISSUE THREAD

**Issue by cypherdare** [libktx/ktx#226]
It would  be nice to have `removeAll(predicate)` (filter in place), and possibly `retainAll` (although it's a bit redundant).

Side question: why doesn't Pooledlist implement MutableIterable? It would be nice to have all those stlib extension functions available.

**Comment by czyzby** [comment]
That's a good suggestion, would you like to submit a PR?

> Side question: why doesn't Pooledlist implement MutableIterable? It would be nice to have all those stlib extension functions available.

Probably because LibGDX don't implement any stdlib collections interfaces either, but I don't see why we couldn't add this.

**Comment by cypherdare** [comment]
Yes, I'll take it on. I can try making PooledList a MutableIterable as well. I don't know the reasoning behind the Gdx classes not implementing Collection.

**Comment by czyzby** [comment]
Me neither, and honestly it's been tedious to write any extensions for them, as they do not share any custom interfaces either.

**Comment by czyzby** [comment]
Thanks for another great contribution @cypherdare, the new utilities are currently being uploaded via snapshot releases.

By the way, I'd like to publish another beta release soon, but if you've got any more ideas or plan more contributions, let me know. We can wait for #227.

**Comment by cypherdare** [comment]
I'm not entirely sure I'll get to #277 before January, so don't wait if you want to get it out sooner than that.

**Comment by czyzby** [comment]
That's fine, take your time.
