### ISSUE TITLE
Ranges for randoms idea

### ISSUE THREAD

**Issue by cypherdare** [libktx/ktx#227]
I make a lot of from-scratch particle effects for my live wallpapers (so I'm not limited by the GDX particle editor's features), and have found Kotlin ranges to be very helpful for very quickly tweaking values. I think this could be helpful anywhere you have something that spawns something in a game, whether it's a particle or enemy. Or for any procedural generator.

So I made some functions that make it even faster to tweak ranges. Operator functions that let you add or multiply constants by the endpoints of the range. Or defining a range by a center and tolerance. And then functions that return a random value from within the range.

For example, here's a simple version of something I've been working on.

```Kotlin
class ParticleLayer (val xStart: ClosedRange<Float>, 
        val yStart: ClosedRange<Float>, 
        val size: ClosedRange<Float> ) {
    private val particles = GdxArray<Particle>()
    //...

    fun update (delta: Float) { /* Updates particles and spawns them when necessary. */ }

    private fun spawnParticle() {
        val particle = particlePool.obtain()
            initialize(xStart.random(), yStart.random(), size.randomGaussian())
        particles.add(particle)
    }
}
```

I have multiple layers of particles, and the ones in the foreground and background are bigger to look out of focus (and move faster but I'm omitting that for the example).

So I first made one particle layer. As I tweak the values, instead of continually typing in new ranges, I can shift them around easily by adding a value:

```Kotlin
val layers = listOf(
    ParticleLayer(xStart = (-0.5f..0.5f) + 0.2f, // My particles needed to have their center shifted to look good
        yStart = 1.2f..2.5f,
        size = 1.3f..1.7f)
)
```

And after getting that looking good, I can copy-paste to get a new layer and then tweak the size range with simple multiplication:

```Kotlin
val layers = listOf(
    ParticleLayer(xStart = (-0.5f..0.5f) + 0.2f,
        yStart = 1.2f..2.5f,
        size = 1.3f..1.7f
    ),
    ParticleLayer(xStart = (-0.5f..0.5f) + 0.2f,
        yStart = 1.2f..2.5f,
        size = (1.3f..1.7f) * 1.3f
    )
)
```
 
Here are the functions I have in my personal library so far:

```Kotlin
fun ClosedRange<Int>.random() = MathUtils.random(endInclusive - start) + start
infix fun Int.amid(tolerance: Int) = (this - tolerance)..(this + tolerance)
fun ClosedRange<Float>.random() = MathUtils.random() * (endInclusive - start) + start
fun ClosedRange<Float>.randomGaussian() = com.cyphercove.audioglow.core.randomGaussian() * (endInclusive - start) + start
fun ClosedRange<Float>.randomTriangular() = MathUtils.randomTriangular(start, endInclusive)
fun ClosedRange<Float>.randomTriangular(normalizedMode: Float) = MathUtils.randomTriangular(start, endInclusive, normalizedMode * (endInclusive - start) + start)
operator fun ClosedRange<Float>.times(multiplier: Float) = (start * multiplier)..(endInclusive * multiplier)
operator fun ClosedRange<Float>.times(multiplier: Int) = (start * multiplier)..(endInclusive * multiplier)
operator fun ClosedRange<Float>.plus(addend: Float) = (start + addend)..(endInclusive + addend)
operator fun ClosedRange<Float>.minus(subtrahend: Float) = (start - subtrahend)..(endInclusive - subtrahend)
infix fun Float.amid(tolerance: Float) = (this - tolerance)..(this + tolerance)
```

**Comment by czyzby** [comment]
That's a very nice utility, good idea. Would you like to contribute some of your utilities from the personal library?

**Comment by cypherdare** [comment]
I think I'll finish the project I'm working on so it has a chance to mature a little more. Should be two or three weeks, and then I can submit a PR.

**Comment by czyzby** [comment]
Don't feel rushed, but any updates on this @cypherdare? If you need more time, I can do an earlier release of 1.9.10-b4, since there's a new KTX module available. Thanks.

**Comment by cypherdare** [comment]
I can put something together in the next couple days. You think it should go in a new file `math/ranges.kt`?

I'm not sure of appropriate tests for random number generators. These will mostly be based on gdx.MathUtils, so there's not a lot here that can go wrong.

I originally had a concern that the boxing/unboxing might cause GC hiccups. If that were the case, it might possibly be better not to use the stdlib ranges which box the values. But even in my live wallpaper running a relatively heavy particle system that queries several ranges, I didn't come across any issues on an old phone. Maybe ANT has some optimizations for this case where the boxed variable immediately gets unboxed. In any case, I don't think we would want to go so far as to create an alternative to the built-in classes because the usefulness of this feature largely has to do with concise syntax. A particle system would have to be spawning many particles on *every* frame for this to really be an issue, and that is an unlikely scenario. And this may more typically be used to tweak parameters in a rogue system where the spawn rate would be far lower.

**Comment by czyzby** [comment]
> I can put something together in the next couple days. You think it should go in a new file `math/ranges.kt`?

If you feel like this would significantly increase the size of the current file, go ahead.

> I'm not sure of appropriate tests for random number generators.

Setup a fixed random seed. Repeat the rolls multiple times. Check if the random values are in expected ranges. We could even go a step further and check the approximate distribution.

> These will mostly be based on gdx.MathUtils, so there's not a lot here that can go wrong.

LibGDX is not really unit-tested, it wouldn't be the first time we'd discover some bugs. :)

> I originally had a concern that the boxing/unboxing might cause GC hiccups. If that were the case, it might possibly be better not to use the stdlib ranges which box the values. 

Shouldn't be an issue unless you roll thousands of numbers each frame. Still, if you're concerned you could check if inlining the extension methods changes the generated bytecode not to box the values.

I like the idea of extending built-it ranges. Custom classes designed solely for rolling numbers seem like and overkill - you might as well just use `MathUtils` static methods if boxing becomes an issue.

**Comment by cypherdare** [comment]
I asked about creating a file because I'm not sure there is any existing file it naturally would go in. The existing `math/` files are named for vectors and matrices.

[Here's an initial pass](https://gist.github.com/cypherdare/499c8a2c77cfd949eb5453de6c9d3f5b) if you want to start looking it over as I start writing tests. 

The stdlib already has an` IntRange.random()` function that uses `kotlin.Random`. I created an overload that lets you pass a `java.util.Random` so `MathUtils.random` can optionally be used. 

The stdlib doesn't have this for Float ranges, possibly because the semantics of `endInclusive` are contrary to how Random produces end-exclusive values. I think the ambiguity is acceptable since the difference is negligible in almost any possible use case. I noted it in the docs.

**Comment by czyzby** [comment]
Looks good so far.

**Comment by czyzby** [comment]
Thanks for the contribution @cypherdare!
