### ISSUE TITLE
Missing touchDown / touchUp scene2d extensions?

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#238]
Hi,

I think that there are touchdown/touchup extensions missing in the actor ktx extensions or maybe that is on purpose.

What I am missing is a way to define a `touchDown` and `touchUp` callback for buttons where I want to react when they get pressed and released.

E.g. when you press the JUMP button the player should jump but when you release it he should cancel the jump and fall down again.

Click and Change did not work for me because click seems to only react when releasing the button and change only reacts on changes which means the first press is a trigger because the button gets "checked", releasing will not trigger anything and the next press will trigger it again.

What worked for me is the touchDown and touchUp events of the ClickListener.

The extension could look like this?

```kotlin
inline fun Actor.onTouch(
        crossinline touchDownListener: () -> Unit,
        crossinline touchUpListener: () -> Unit
    ): ClickListener {
        val clickListener = object : ClickListener() {
            override fun touchDown(event: InputEvent, x: Float, y: Float, pointer: Int, button: Int): Boolean {
                touchDownListener()
                return true
            }

            override fun touchUp(event: InputEvent?, x: Float, y: Float, pointer: Int, button: Int) = touchUpListener()
        }
        this.addListener(clickListener)
        return clickListener
    }
```

It could then be used like this

```kotlin
actor.onTouch(
                touchDownListener = { this.gameEventManager.dispatchInputKeyPressEvent(Key.JUMP) },
                touchUpListener = { this.gameEventManager.dispatchInputKeyReleaseEvent(Key.JUMP) }
            )
```

Would this be useful or do you suggest a different approach for such a use-case?

**Comment by czyzby** [comment]
I believe this wasn't added, as `onClick` covers most use cases and this utility would require two lambdas or a boolean attribute with up/down state. We could add something similar to your suggestion.

**Comment by czyzby** [comment]
Separate `onTouchDown` and `onTouchUp` extension methods could also do the job, although you'd add 2 separate listeners.

**Comment by Quillraven** [comment]
I can look into it in more detail next weekend. I think having 2 separate listeners would not be a big issue as usually you do not have hundreds of those listeners so it will not have a big impact in my opinion.

Taken from the actors documentation:
```kotlin
import ktx.actors.*

label.onClick { 
  println("Label clicked!")
}

label.onClickEvent { inputEvent, actor ->
  // If you need access to the original InputEvent, use this expanded method variant.
  println("$actor clicked by $inputEvent!")
}
label.onClickEvent { inputEvent, actor, x, y ->
  // If you need access to the local actor click coordinates, use this expanded method variant.
  println("$actor clicked by $inputEvent at ($x, $y)!")
}
```

Maybe it would be possible to have a `onTouchEvent` extension like
```kotlin
button.onTouchEvent{ event, actor, state -> ... }
```
where `state` would indicate if it is pressed or released (either a boolean or maybe there is a libgdx Touchstate enum available).


The only downsite with having two separate methods is that we cannot chain them since they return the listener instead of the actor. But that could also be solved by having:
```kotlin
// this will not work as touchdown is returning the listener
button
  .onTouchDown {}
  .onTouchUp {}

// this should work
button.run {
  onTouchDown{}
  onTouchUp{}
}
```

**Comment by czyzby** [comment]
`onTouchEvent` and `onTouchDown` + `onTouchUp` returning listeners sound good.

**Comment by czyzby** [comment]
Thanks for reporting the issue and the contribution @Quillraven, `ktx-actors` snapshot release with the listeners should be available soon.

**Comment by Quillraven** [comment]
Always happy when I can help out!

I had an appointment with my eye doctor yesterday and I always get some drops in my eyes that make me unable to see close range for a couple of hours. 
That is why I was not able to fix the Readme myself, sorry.

**Comment by czyzby** [comment]
You don't have to apologize, this was a very easy fix. :) Thanks again for the contribution!
