### ISSUE TITLE
Update to Gradle 6

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#243]
Gradle 6.1.1 is available as of writing this issue. A major update is a good opportunity to rewrite old publishing plugins setup and try out the (now possibly stable) Kotlin scripting. #18

**Comment by maltaisn** [comment]
Gradle kotlin scripting seems stable to me, I don't have any issues with it, and IDE support is better than it was. There's not many advantages to using it honestly, but at least it works. I'm fairly comfortable working with it so I could make a pull request if you want.

**Comment by czyzby** [comment]
I believe @aouerfelli already tried to translate our build configuration and considered it a regression, see #18. Migrating to Kotlin scripting could be a good excuse to rewrite the Maven publishing part - I believe we're using some outdated plugins for that.

If you're OK with working on it and want to submit a PR, I'll be happy to review it and test it out.

**Comment by maltaisn** [comment]
I think you could use bintray, it comes with a great gradle plugin. It would remove the need for the `withGroovyBuilder` workaround need with kotlin scripting. The plugin also has an option to sync with maven central so that would remove the need for the nexus staging plugin. I'm not sure if it will handle the `provided` configuration correctly though, and I'm not sure if it allows publishing to the snapshots repository. LibKTX is already on jcenter, do you already use it or was it synced with maven central automatically maybe?

That said it does seem like a lot of work for little results.

**Comment by czyzby** [comment]
JCenter syncs automatically, I believe.

If you'd like to prepare basic Bintray Gradle config, I could setup KTX on Bintray with Maven Central sync. I think `provided` dependencies would have to be changed to idiomatic Gradle qualifiers (e.g. `runtimeOnly` etc.).

**Comment by Megamiun** [comment]
Hello, @czyzby, is there any opening to work on this? If yes, I would like to try

**Comment by czyzby** [comment]
Thanks @Megamiun, I don't think anyone is working on this right now - you can go ahead and try this. Keep in mind that a while back @aouerfelli translated our Gradle setup to Kotlin [on this fork](https://github.com/aouerfelli/ktx/tree/gradle-kotlin-dsl) (#18), so if you'd like to attempt this as well, you can base your work on that.

**Comment by aouerfelli** [comment]
> Keep in mind that a while back @aouerfelli translated our Gradle setup to Kotlin [on this fork](https://github.com/aouerfelli/ktx/tree/gradle-kotlin-dsl) (#18), so if you'd like to attempt this as well, you can base your work on that.

KTS support for Gradle has definitely come a long way, and this should easily be doable now. That being said, if you want to try it out, I probably wouldn't look at mine since it's severely outdated.

**Comment by czyzby** [comment]
Alright, thanks for the heads up!

**Comment by czyzby** [comment]
@Megamiun migrated our setup to Gradle 6. Thanks for your contribution!
