### ISSUE TITLE
Make Context.register not inlined

### ISSUE THREAD

**Issue by serandel** [libktx/ktx#247]
This nano-change will allow me to introduce a mock Context in my Game class and ignore the register function, so the test will not try to create all the bindings from the actual game. Right now, as register is inlined, there's no way to stop the bindings lambda from running unless I do some ugly workaround like this:

```kotlin
class MyGame(private val context: Context = Context(),
                      private val testBindings: (Context.() -> Unit)? = null)
    : KtxGame<KtxScreen>(null, true) {

    override fun create() {
        context.register(testBindings ?: {
            bindSingleton(this@MyGame)

            // More screens and bindings
    }
}
```

and in testing...

```kotlin
MyGame(mockk<Context>(), {})
```

I think register will be used so rarely that the performance improvement of the inline may be forfeited in favor of clean testing.

**Comment by serandel** [comment]
PR in #246

**Comment by czyzby** [comment]
This utility function is just syntax sugar similar to Kotlin's official `apply`. It's inlined precisely to avoid creating capturing lambdas. In the future, I plan on expanding this method with Kotlin contracts (with `InvocationKind.EXACTLY_ONCE`), so you can assign final variables from within the building block.

It seems there's an issue with your constructor in the first place. You generally should never modify the API of your classes to cater for tests, i.e. `testBindings` or anything purely tests-related should not be a part of your actual application API.

If you want to avoid major rewriting, I suggest adding a specialized component that allows you to check for the profile of the application. E.g. you could use a sealed `Profile` class with two singleton implementations: `Test` and `Production`. Then you could control the initiation logic of your game like this:

```kotlin
if (context<Profile>() == Production) {
  context.register {
    // ...
  }
}

You could add all of the required components in tests and set the `Profile` to `Test`, so that your game instance does not modify the context at all.
