### ISSUE TITLE
Mistakes in ktx-json wiki

### ISSUE THREAD

**Issue by Divelix** [libktx/ktx#248]
I'm trying to figure out how to use ktx JSON extensions and stumbled a little. In examples class `Cards` is being used, but there is no implementation of it. According to output json it is just integer value. Moreover, there is "pos" field occurs, while Player class has "position". 

Ok, I tried to implement this examples: `Vector2AsArraySerializer()` works fine, but I get error when trying to read array of values (Cards in example, I switched it to Int but still get error). Error is `java.lang.IllegalStateException: readValue(T::class.java,… else jsonData.get(name)) must not be null`.

EDIT: I've just found `jsonTest.kt` and figured out how to deal with everything 😊.

**Comment by czyzby** [comment]
Thanks for bringing this to my attention, I'll test and correct all of the examples.

**Comment by Divelix** [comment]
I have a question. In `jsonTest.kt` there is `Custom` class:
```kotlin
private data class Custom(
        var float: Float = 0f,
        var simple: Simple = Simple(),
        var list: List<Simple> = emptyList()) : Json.Serializable {

    override fun read(json: Json, jsonData: JsonValue) {
        float = json.readValue(jsonData, "float")
        simple = json.readValue(jsonData, "simple")
        list = json.readArrayValue(jsonData, "list")
    }

    override fun write(json: Json) {
        json.writeValue("float", float)
        json.writeValue("simple", simple)
        json.writeValue("list", list)
    }
}
```
and when we serialize it, we get `List<Simple>` that looks like that:
```json
list: [
	{
		class: com.divelix.skitter.screens.Simple
	}
	{
		class: com.divelix.skitter.screens.Simple
		int: 1
	}
	{
		class: com.divelix.skitter.screens.Simple
		int: 2
	}
]
```
How can I get rid of this annoying `class: com.divelix.skitter.screens.Simple` lines and get that list as:
```json
list: [
	{}
	{int: 1}
	{int: 2}
]
```
Libgdx wiki says that I should use `setElementType`. I tried to use `json.setElementType<Custom, Simple>("list")` in read/wtite methods, but it doesn't help.

**Comment by czyzby** [comment]
The [second section of the official JSON wiki article](https://github.com/libgdx/libgdx/wiki/Reading-and-writing-JSON) talks about this, it should be relatively easy to translate to Kotlin. Let me know if you have any further problems with the API.

**Comment by czyzby** [comment]
>  I tried to use `json.setElementType<Custom, Simple>("list")` in read/write methods of `Custom`, but it doesn't help.

You should probably do that once for each serializer after initiation, not in the `read`/`write` methods. See how the official wiki does that once after creating a `Json` object:

```java
Json json = new Json();
json.setElementType(Person.class, "numbers", PhoneNumber.class);
```

**Comment by czyzby** [comment]
I've rewritten the examples, all of them should compile after minor modifications (e.g. adding missing serialized classes, usually given in other examples).

**Comment by czyzby** [comment]
You can find the latest documentation [on `develop` branch](https://github.com/libktx/ktx/tree/develop/json).
