### ISSUE TITLE
Image builder in `vis` that takes texture as prameter

### ISSUE THREAD

**Issue by Divelix** [libktx/ktx#251]
As for now, `WidgetFactory` in `vis` module has `image` functions that takes only `Drawable` and `String` (drawableName), while `VisImage` class has also overloads for ninepatches, textures and texture regions. Would be nice if you add them to ktx too (especially the one that takes `Texture`).

**Comment by czyzby** [comment]
Factory methods using `Texture`, `TextureRegion` and `NinePatch` were added. They will be available soon in the latest snapshot release. Thanks for the suggestion.
