### ISSUE TITLE
Add mutating plusEquals operator and non-mutating plus operator to collections module

### ISSUE THREAD

**Issue by Divelix** [libktx/ktx#252]
It seems natural to use `+=` to add elements to set/array/map. Would be nice to see it in `collections` module.

**Comment by czyzby** [comment]
As far as I know this already works, as `plus` operators are mutating and returning the same collection, so `+=` have a similar effect.

**Comment by Divelix** [comment]
But `plus` returns new collection. It is more useful to add elements to existing collection with `+=`, isn't it?

**Comment by czyzby** [comment]
The thing is, we went with the LibGDX approach of "do not create new objects unless necessary" and `plus` [do not create new collections](https://github.com/libktx/ktx/blob/master/collections/src/main/kotlin/ktx/collections/arrays.kt#L136-L144). This goes against Kotlin principles and we might change that in the future, now that I think about it.

**Comment by Divelix** [comment]
Oh, sorry, I just noticed that imported `ktx.collections.gdxSetOf` instead of `ktx.collections.*`. So I was using standard kotlin `+` operator...

**Comment by czyzby** [comment]
No problem. I'll leave this issue open, as we might eventually move to separate `plus` and `plusAssign` operators for non-mutating and mutating behaviour respectively.
