### ISSUE TITLE
KtxInputAdapter and InputAdapter are identical

### ISSUE THREAD

**Issue by Divelix** [libktx/ktx#253]
What's the point of `KtxInputAdapter` if libgdx has `InputAdapter` class? Readme in `app` module says that `InputAdapter` is abstract, but it is not. Both of these classes have identical code right now.

**Comment by czyzby** [comment]
They are not identical.

LibGDX `InputAdapter` is a _class_ that you have to _extend_.

```java
// Java LibGDX adapter:
public class InputAdapter implements InputProcessor
```

KTX `KtxInputAdapter` is an _interface_ that you can _implement_. It leverages default interface method implementations to provide similar functionalities to `InputAdapter` (i.e. you override only the methods that you need).

```kotlin
// Kotlin KTX adapter:
interface KtxInputAdapter : InputProcessor
```

You can implement multiple interfaces, but you can only extend one class, which makes `KtxInputAdapter` more flexible.

**Comment by czyzby** [comment]
I've fixed the README file, as `InputAdapter` is not an abstract class (it's still a class though, so the point still stands).
