### ISSUE TITLE
Add kotlinx-coroutines-core dependency automatically when using ktx-assets-async

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#263]
Hi,

I forgot to mention one thing for the assets-async module. Would it be possible to automatically add the `kotlinx-coroutines-core` dependency when using this module (api instead of implementatin)?

I don't know if this is possible. Otherwise, I would at least mention it in the documentation and in the additional documentation section I would link to the official kotlin coroutine article.

Also, the Readme.md still mentions 1.9.10-b4 as latest version instead of 1.9.10-b5 ;)

**Comment by czyzby** [comment]
> Would it be possible to automatically add the `kotlinx-coroutines-core` dependency when using this module (api instead of implementatin)?

Possible? Yes. Do we want to do it? Originally the idea was that the user chooses any Kotlin (and Kotlin Coroutines) version, depending on the need, and KTX just works. However, I do recall a bug where you had to use a specific version of coroutines that KTX was compiled against, so I think we might need to reconsider. I'll think about this and leave this issue as open for discussion.

>  Also, the Readme.md still mentions 1.9.10-b4 as latest version instead of 1.9.10-b5 ;)

Do you mean the main README? I think there's a line about updating it to the latest version. I wanted to avoid updating README constantly after each update, but I guess it makes sense. The latest version is correctly shown on the website though.

**Comment by Quillraven** [comment]
> Do you mean the main README? I think there's a line about updating it to the latest version.

Exactly that one. Isn't there a way to also automatically link to the latest version? I noticed that the kotlin documentation always shows the latest version in their example snippets whenever there is a new release and I cannot imagine that someone is manually updating that every time :D

However, I have no idea how to do it, sorry :(

**Comment by czyzby** [comment]
> I noticed that the kotlin documentation (...)
I think they aren't using GitHub for that. JetBrains/kotlin has a similar Maven Central badge that we're using.

> However, I have no idea how to do it, sorry :(

I don't think you can do it with pure markdown. You can link to external services that fetch the latest version. That's how we get the badges that link to Maven Central in module READMEs, for example. I'll think of something.

**Comment by czyzby** [comment]
I updated the README to include an extra badge in the Gradle section.

If the badge loads, it shows up like this:

![image](https://user-images.githubusercontent.com/11707612/79259514-208fb980-7e8d-11ea-92a8-622fbf16919d.png)

If the badge lags (which happens), it will be replaced with a `Maven Central` link. Either way, clicking on the link or the image takes you to the Maven Central repository site where you can check the latest versions.

**Comment by Quillraven** [comment]
sounds good! 👍

**Comment by czyzby** [comment]
I'll close this issue for now. All Kotlin libraries are added as `compileOnly`, so that user's version is always preferred. We might reconsider this approach later on, e.g. for a non-beta release (#73).
