### ISSUE TITLE
ktx-math creates new vector instances instead of modifying the original one

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#264]
Hey,

it is me again (I know I am annoying :P). Yesterday, I noticed that the documentation for ktx-math is a little bit misleading in my opinion and not aligned with the original libgdx documentation.

Take e.g. the `add` function:
```kotlin
/**
 * @param vector3 values from this vector will be added to this vector.
 * @return this vector for chaining.
 */
operator fun Vector3.plus(vector3: Vector3): Vector3 = Vector3(this.x + vector3.x, this.y + vector3.y, this.z + vector3.z)
```

```Java
@Override
public Vector3 add (final Vector3 vector) {
	return this.add(vector.x, vector.y, vector.z);
}

/** Adds the given vector to this component
 * @param x The x-component of the other vector
 * @param y The y-component of the other vector
 * @param z The z-component of the other vector
 * @return This vector for chaining. */
public Vector3 add (float x, float y, float z) {
	return this.set(this.x + x, this.y + y, this.z + z);
}
```

If I read it correctly, the first one (libktx) creates a new `Vector3` instance every time I use `a + b`. The second one (libgdx) modifies the original instance every time I use `a.add(b)`.
Both functions mention `return This vector for chaining` which is actually wrong for libktx because it returns a new instance.

Am I correct? Or am I reading it wrong? If correct, either adjust the documentation or modify the original instance. I personally would prefer to modify the original instance.

**Comment by czyzby** [comment]
This is deliberate, but the documentation is out of date. See #130.

Originally I went with LibGDX approach of mutating existing objects, but eventually we decided to follow [the Kotlin guidelines](https://kotlinlang.org/docs/reference/operator-overloading.html) of operator overloading and mutate the object only with assignment operators (e.g. `+=`, `-=`). In fact, `-`, `++` and `--` should also follow this pattern and I'll change that in this issue.

If you want to avoid creating a new object to e.g. add values to an existing vector, either use the `+=` operator or the original LibGDX API.

> it is me again (I know I am annoying :P)

Not at all, you're actually helping a lot with your suggestions. The invalid documentation is clearly a human error.

**Comment by czyzby** [comment]
Now all operators are following the Kotlin guidelines. This might seem to create some unnecessary garbage, which LibGDX devs tend to worry about, but I believe this approach is safer in terms of unexpected application logic bugs - such as accidentally mutating an instance of vector/matrix that we were trying to use for a mathematical operation.

To sum up - if you worry about garbage collection, use assignment operators such as `+=` or `-=` to mutate existing instances. If you cannot get away with these simple operators and want to avoid creating unnecessary vector/matrix instances for your calculations, switch to original mutating LibGDX API.

**Comment by Quillraven** [comment]
Thanks for the clarification and adjustments!
