### ISSUE TITLE
Evaluate GitHub Actions as an alternative to Travis

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#266]
- [x] Automatic tests running on commits and pull requests to the `master` and `develop` branches.
- ~Uploading libraries to GitHub Packages on `master` commits.~
- [x] Uploading snapshots to Maven Central on `develop` commits.
- [x] Building and publishing Dokka documentation to GitHub Pages on `master` commits.

---

Travis was running smoothly up until recently, where we had some problems with Travis/GitHub integration - builds were still being triggered correctly, but links to builds in commits and pull requests broke completely. You had to navigate to project page in Travis manually to see build statuses. Travis integration had to be removed and added back again to fix the issue. #11

I tested GitHub Actions in some private projects and they seem to be working very well so far. They integrate better with GitHub (obviously) and make it possible to add some nice features that I wanted to include a while back, but was hesitant to set up in Travis since they required e.g. pushing rights to the repository or Maven Central.

The `dokkaJavadoc` task will probably have to be removed as well, as it frequently goes into an infinite loop in `vis` module for some reason. It was added strictly for Javadoc publishing to Maven Central, but I can't see anyone actually relying on these Javadocs, as Kotlin sources artefacts are much more useful in IDE and Dokka pages published on GitHub are a better source of documentation for Kotlin.

**Comment by czyzby** [comment]
Using GitHub packages would require adjusting the publishing settings in `build.gradle`, possibly by adding another repository or conditionally choosing repositories depending on the environment. Either way, it requires extra setup for little value for the users, since Maven Central is already pretty convenient to use.

**Comment by czyzby** [comment]
Snapshots are now automatically published to Maven Central snapshots repository after commits to `develop`. Auto-generated Dokka documentation is now built after each push to master and available [here](https://libktx.github.io/ktx/). Tests are now performed by GitHub actions/workflows rather than Travis.

@Quillraven I'd appreciate it if you tested the latest snapshot release and had a look at the documentation page, just in case. Thanks.

**Comment by Quillraven** [comment]
I tried out the snapshot today and it seems to work just fine. No problems on my end.

Will also read some of the documentation on the weekend where I also want to add a new PR for some ashley extensions.
