### ISSUE TITLE
Rewrite VisUI DSL module

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#269]
- [x] Extend `ktx-scene2d` module in `ktx-vis`.
- [x] Unify `ktx-vis` and `ktx-scene2d` APIs and tests.
- [x] Replace `VisDsl` marker with `Scene2dDsl` marker.
- [x] Inline `ktx-vis` factory methods.
- [x] Improve `ktx-vis` documentation.

---

`ktx-scene2d` was originally added by me, while around the same time `ktx-vis` was created by the VisUI author. While the original plan was to either make `ktx-vis` extend `ktx-scene2d` or to have both extend a common GUI building module (#9), they remained separate due to different approaches and lack of crucial features at the time (e.g. default values for lambda parameters in inlined methods). As an example, `ktx-scene2d` originally had 2 or 3 factory methods for each actor - with inlined building lambda, without the lambda parameter and optionally top-level factory for parental actors. Such code duplication was unacceptable in `ktx-vis`, since VisUI had a lot more actors to cover.

Since then, both Kotlin features and `ktx-scene2d` API have improved and stabilized (#46, #48, #94, #268). Especially after #268, `ktx-vis` approach will feel vastly different to `ktx-scene2d`, which makes the transition between the two more difficult. Besides, `ktx-vis` lacks some useful features provided by `ktx-scene2d`:
- inlined factory methods for improved performance;
- simple creation of top-level actors that are not parental;
- complete documentation of all factory methods and their parameters.

The goal of this issue is to unify both modules, so that `ktx-vis` would extend `ktx-scene2d` and provide a similar set of features, rather than remain an alternative.

**Comment by czyzby** [comment]
@kotcrab Just a heads up: I finally unified the GUI modules. I believe we didn't do this in the first place because there were no default values for lambda parameters in inlined methods, among other things. Anyway, if you want to take a look and check if anything is missing (maybe something from the latest VisUI versions), you can find the latest code on the [`develop`](https://github.com/libktx/ktx/tree/develop/vis) branch

**Comment by kotcrab** [comment]
Nice! Honestly I don't remember which VisUI version was this originally based on but I doubt anything important is missing. Most [VisUI changes](https://github.com/kotcrab/vis-ui/blob/master/ui/CHANGES.md) were bug fixes after certain point.
