### ISSUE TITLE
Additional ktx-ashley extensions

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#270]
From what I know it is a best practice in ashley to remove entities at the end of a frame or at the beginning, when using a `PooledEngine` because otherwise you sometimes get strange behaviors when removing and adding entities within the same frame.

Therefore, I use a `RemoveComponent` in most of my projects that is added to an entity to mark it as being removed. Some `IteratingSystems` then exclude entities with a `RemoveComponent`. A `RemoveSystem` is then added at the end or at the front of all engine systems which then removes such entities from the engine.

There is no kotlin extension for that, from what I have seen and that's why you have to write something like 

```kotlin
entity.add(engine.createComponent(RemoveComponent::class.java))
```

Might be a good idea to have the existing `with` function from the creation DSL for such things?

```kotlin
entity.with<RemoveComponent>
```

or something similar?

Also, very rarely you need to access certain systems from the engine. Here, I also could not find a kotlin counterpart and the current code is like:

```kotlin
engine.getSystem(SomeSystem::class.java)
```

Would it be possible to have something like:

```kotlin
engine[RemoveSystem::class]
// or
engine<RemoveSystem>
```

I could try something out on the weekend and provide a PR. What would be the preferred solutions?

**Comment by czyzby** [comment]
I'll have to review Ashley module to give you more insights. You're welcome to submit the PR, if you already have a prototype of these features.

@Jkly Thoughts?

**Comment by czyzby** [comment]
@Quillraven 

`Entity` has no access to `engine` after creation, so we would either have to return `EngineEntity` (which has the `with` extension for adding components) or add a utility method such as `Entity.addComponent<Type>(engine)`.

```kotlin
inline fun <reified C: Component> Entity.addComponent(engine: Engine, configure: (@AshleyDsl C).() -> Unit): C {
  val component = engine.create(configure)
  add(component)
  return component
}

// Usage example:
class Transform(var x: Float = 0f, var y: Float = 0f) : Component
fun example(entity: Entity, engine: Engine) {
  entity.addComponent<Transform>(engine) {
    x = 10f
    y = 10f
  }
}
```

As for the system, we could add something like this:

```kotlin
inline fun <reified S: EntitySystem> Engine.getSystem() = getSystem(S::class.java)

// Usage:
engine.getSystem<MySystem>()
```

If you'd like to refine my examples and write the tests, you're welcome to submit a PR. Otherwise I'll look into it during the weekend.

**Comment by Quillraven** [comment]
I can do that tomorrow,no problem  :)
