### ISSUE TITLE
Allow manually adding entity to engine

### ISSUE THREAD

**Issue by ronjunevaldoz** [libktx/ktx#283]
Some functionally need to allow manually adding entity to engine. But the current `engineEntity` builder does not have ano options for this.

**Comment by czyzby** [comment]
What is your use case? I don't think `EngineEntity` was designed for direct use other than via `Engine.entity` extension method, and `Entine.entity` automatically adds the entity to the engine after it is created. Can you post a code sample of what you'd like to achieve?

**Comment by czyzby** [comment]
If I'm understanding this issue correctly, we will not be adding a method to `EngineEntity` that allows to add it to an engine. It's possible to do - even with the current API - but this is not how it was designed to be used.

The preferred way of creating entities (and accessing `EngineEntity`) is via `Engine.entity` extension method. This will automatically add the entity to the engine.

To add components to an existing entity, you do not have to wrap it with `EngineEntity`. Instead, use:
* `Engine.create` to create new components and `+=` to add them to an entity.
* `Entity.addComponent` to configure and add components to an existing entity.
* The newly added `Engine.configureEntity` (available via snapshot release) that exposes `EngineEntity` DSL for an existing entity.

If you really want to use `EngineEntity` directly, it is already possible to add the entity to the engine, as both are exposed. All you have to do is call `engine.addEntity(entity)` (if `EngineEntity` is captured as `this`). Here's an extension method that might prove useful:

```kotlin
fun EngineEntity.addToEngine() {
  this.engine.addEntity(this.entity)
}
```

In other cases, if you're managing `Entity` lifecycle manually, it's easy enough to add to an engine as it is, and wrapping it with `EngineEntity` manually provides no significant advantages over existing utilities.

If that doesn't solve your problem, please reopen the issue and post code samples of what you'd like to achieve.
