### ISSUE TITLE
Add Color destructuring syntax support

### ISSUE THREAD

**Issue by heyheyIvan** [libktx/ktx#284]
Hi!
I suggest adding support for Color destructuring syntax.
It would be great to be able to write code such as:
```kotlin
val (red, green, blue, alpha) = myColor
```

The same is implemented in [androidx](https://developer.android.com/reference/kotlin/androidx/ui/graphics/Color#component1())

**Comment by czyzby** [comment]
Thanks again for the contribution, this seems like a useful utility!
