### ISSUE TITLE
Actor onEnter and OnExit extension functions

### ISSUE THREAD

**Issue by v79** [libktx/ktx#286]
I wanted to change the style of a label on mouse hover. `onEnter` worked fine:
```kotlin
label("Load Game").cell(row = true).apply {
	onEnter {
		style = skin["mainMenuHover",Label.LabelStyle::class.java]
	}
}
```
But there's no corresponding `onExit` function. I've written one now, but wondered if there was documentation around which scene2d stage elements have actions, and which do not, and which actions they have?

For reference, here is my `onEnter` function. This is all new to me so hope I'm coding it correctly.
```kotlin
inline fun Label.onExit(crossinline listener: () -> Unit): InputListener {
	val eventListener = object : InputListener() {
		override fun exit(event: InputEvent?, x: Float, y: Float, pointer: Int, toActor: Actor?) {
			super.exit(event, x, y, pointer, toActor)
			return listener()
		}
	}
	this.addListener(eventListener)
	return eventListener
}```

**Comment by czyzby** [comment]
I'll be honest, I'm not sure where you got the `onEnter` extension from. I've search the entire project KTX project and I don't think it's ours. Can you go to the source of `onEnter` (CTRL + B) and post it here, @v79?

Now that you mention it, both of these functions could be pretty useful. They will be added to the `ktx-actors` module.

**Comment by czyzby** [comment]
I also improved the API of the existing event listener methods, so that the `apply` is not necessary. Event listeners will now consume the actor as `this`.

**Comment by v79** [comment]
> I'll be honest, I'm not sure where you got the `onEnter` extension from. I've search the entire KTX project and I don't think it's ours. Can you go to the source of `onEnter` (CTRL + B) and post it here, @v79?

Perhaps I shouldn't raise defects after 10pm - apologies! I had written an `onEnter` extension function on `Actor` for debugging purposes and had long forgotten about it. My fault. But thank you for making KTX so easily extensible.

I suppose there is a wider question about what scene2d elements should support what actions. My inexperience with LibGDX meant I learned about `Label` long before `TextButton`. And I've a lot still to learn :).

**Comment by czyzby** [comment]
I think `onCursorEnter`/`onCursorExit`/`onCursorHover` could be very useful extensions, so thank you for bringing it up. I'll leave the issue as open and implement similar official extensions. :)

**Comment by czyzby** [comment]
Thanks @mmilenkov for the contribution!
