### ISSUE TITLE
Explicitly implement Disposable interface in application utilities

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#288]
Classes such as `KtxApplicationAdapter`, `KtxGame` and `KtxScreen` already provide no parameter `dispose` function that matches the `Disposable` interface due to `ApplicationListener` or `Screen` API. Explicitly implementing this interface allows to leverage existing `Disposable` utilities.

**Comment by steven-peralta** [comment]
I'm having issues related to this change here: #309
