### ISSUE TITLE
LibGDX 1.9.11 released

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#292]
I see that they released 1.9.11 on github. Time to change the libktx versioning and make a new release for 1.9.11?  ;)

**Comment by czyzby** [comment]
Yup. Thanks for the heads up, I'll make a release this week.

**Comment by czyzby** [comment]
Updated the project to LibGDX 1.9.11 without any major issues. It seems only a single class was renamed.

**Comment by czyzby** [comment]
@Quillraven I'd like to wait for VisUI to be updated to LibGDX 1.9.11 to ensure that there are no compatibility issues. I'll upload a stable version once it's released. You can already use the `1.9.11-SNAPSHOT` version for now, although it doesn't have any new features other than library updates as of writing this comment.

**Comment by Quillraven** [comment]
cool, thank you!

**Comment by czyzby** [comment]
`1.9.11-b1` is being released as I'm writing this comment, it should be available shortly.
