### ISSUE TITLE
Image builder without Skin styles

### ISSUE THREAD

**Issue by Divelix** [libktx/ktx#299]
Now `image` builder have only one option - define skin and stylename. But I merge my sources into atlases and skins only before release (it is much faster to debug and make changes with direct access to texture files).

Right now I use 'ktx-vis' just to make things like:
```kotlin
visImage(Texture("texture.png"))
```
as VisUI had `Image` constructors for Texture/Drawable/NinePatch/etc. before official Libgdx added them. But now they are in official libgdx, so it would be nice to have them in `ktx-scene2d`.

Another handy thing would be to add `image` to `skin` builder and use it like:
```kotlin
// define in skin
skin {
    image("myImage") {
        drawable = ... // put drawable here from texture or smth
    }
}
...
// use in ui
table {
    label("Text")
    image("myImage") {
        setSize(50f, 50f)
    }
}
```

**Comment by czyzby** [comment]
Makes sense, thanks for the suggestion. Would you like to try to make a PR with these?

**Comment by Divelix** [comment]
Ok, I will try)

**Comment by Divelix** [comment]
I'm not sure is that good idea to add such syntax:
```kotlin
skin {
    image("myImage") {
        drawable = ... // put drawable here from texture or smth
    }
}
```
as it will be out of general code style in `ktx-style` because all builders there use `addStyle` while `Image` has no style.

**Comment by czyzby** [comment]
> I'm not sure is that good idea to add such syntax (...)

This is already possible due to the original LibGDX `Image` API, as they provided the `getDrawable`/`setDrawable` methods. So the code snippet you posted is valid, and we cannot really prohibit the users from modifying the images like that.

**Comment by czyzby** [comment]
Thanks again for the contribution, the new builders should be available shortly in the snapshot release `1.9.11-SNAPSHOT`.

**Comment by Divelix** [comment]
> This is already possible due to the original LibGDX `Image` API, as they provided the `getDrawable`/`setDrawable` methods. So the code snippet you posted is valid, and we cannot really prohibit the users from modifying the images like that.

I tried to do this and it seems not feasible as `image` builder with string argument already exists in `ktx-style` and it takes drawable name from skin.

**Comment by Divelix** [comment]
Or maybe I just made some mistake? Here is my code:
```kotlin
@SkinDsl
@OptIn(ExperimentalContracts::class)
inline fun Skin.image(
        name: String = defaultStyle,
        init: (@SkinDsl Image).(Image) -> Unit = {}
) {
    contract { callsInPlace(init, InvocationKind.EXACTLY_ONCE) }
    val img = Image()
    img.init(img)
    return add(img, name)
}

@Scene2dDsl
@OptIn(ExperimentalContracts::class)
inline fun <S> KWidget<S>.image(
        name: String,
        skin: Skin = Scene2DSkin.defaultSkin,
        init: (@Scene2dDsl Image).(S) -> Unit = {}
): Image {
    contract { callsInPlace(init, InvocationKind.EXACTLY_ONCE) }
    return actor(skin[name], init)
}
```
And use it:
```kotlin
skin {
    image("myImage") {
        drawable = TextureRegionDrawable(Texture(myImage.png))
    }
}

table {
    image(name = "myImage") // call "name = " to chose my overload fun
}
```

And I get error `No com.badlogic.gdx.scenes.scene2d.ui.Image registered with name: myImage`

**Comment by czyzby** [comment]
@Divelix Oh, I didn't notice you're talking about `skin` rather then Scene2D UI.

We won't add image style builder to `ktx-style`, simply because there isn't one - `Image` has no corresponding `ImageStyle` class. Instead you're expected to pass a drawable name, which is automatically extracted from the `Skin`. I think it works well enough:

```kotlin
// Creates an image that extract "drawableName" texture region from the default skin:
scene2d.image("drawableName")
```

Trying to add an image style on top of that would be inconsistent with original LibGDX API, and likely wouldn't offer much more than the existing methods (unless we add extra configuration properties to the style, but then again - you can configure images with `ktx-scene2d` already).

**Comment by Divelix** [comment]
> We won't add image style builder to `ktx-style`, simply because there isn't one - `Image` has no corresponding `ImageStyle` class. Instead you're expected to pass a drawable name, which is automatically extracted from the `Skin`. I think it works well enough:

Yes, that's what I was talking about above, so I didn't want to make `ImageStyle` crutch. My point was to make possible to use Drawables/Textures/etc. in UI without `TextureAtlas`. As you said, related builders for `@Scene2dDsl` would be there in snapshot. I just wanted to make it possible to initialize graphics resources through skin DSL (to avoid usage of atlasses on debug stage). `Skin` allows to store separate `TextureRegion`s, isn't it? May be you would consider this as redundant feature.

**Comment by czyzby** [comment]
I believe you could add custom regions to the `Skin`, yes. Something like this should work:

```kotlin
  // Skin definition:
  skin {
    set("name", TextureRegion(Texture("custom.png")))
  }

  // Widget builder:
  scene2d.image("name")
```

Afaik `Skin` will automatically convert texture regions to drawables. And while all of this is possible, I think in the end it's more convenient (and possibly more performant) to use texture atlases. I usually setup a [Gradle task](https://github.com/czyzby/bialjam17/blob/master/build.gradle#L36-L43) that packs images with `gdx-tools` directly, but you might also consider using the [third-party GUI](https://github.com/crashinvaders/gdx-texture-packer-gui).

**Comment by Divelix** [comment]
> I believe you could add custom regions to the Skin, yes. Something like this should work:

Yes, that worked for me, thanks. One day I will start to use gradle tasks like a cool guy, but not today)

**Comment by czyzby** [comment]
Just so you know, you can also use operator syntax sugar - something like this should work as well:

```kotlin
skin {
  this["name"] = TextureRegion(Texture("custom.png"))
}
```
