### ISSUE TITLE
Math support

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#3]
- [x] Overloaded operators and simple factory methods.
  - [x] `Vector2`.
  - [x] `Vector3`.
  - [x] `Matrix3`.
  - [x] `Matrix4`.
- ~~Global methods for random numbers using `MathUtil` (?).~~

**Comment by elect86** [comment]
Hi, 

I am working on a glm port [here](https://github.com/elect86/glm), may interest you, guys?

**Comment by czyzby** [comment]
I guess we could this library similarly to how we list KTX alternatives (once its pushed to Maven Central or another repository). `ktx-math` aims to bring Kotlin features to LibGDX math API, while your library seems to be independent of LibGDX altogether.

**Comment by elect86** [comment]
> I guess we could..

list?

**Comment by czyzby** [comment]
Fixed, thanks. ; )

**Comment by czyzby** [comment]
BTW, you can let us know once the library is published.

**Comment by elect86** [comment]
Hi,

 [glm ](https://github.com/kotlin-graphics/glm) is quite mature now, may I add it to the list?

**Comment by czyzby** [comment]
@elect86 Sure, feel free to make a pull request with changes to [math/README.md](https://github.com/libktx/ktx/blob/develop/math/README.md).
