### ISSUE TITLE
Update to the latest Dokka version

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#303]
[Dokka was rewritten](https://blog.jetbrains.com/kotlin/2020/08/dokka-preview-based-on-kotlin-1-4-0-rc/) and now offers a vastly improved generated user interface. There's also built-in support for multimodule projects, which means we no longer need a custom glue index page that links all of the modules.

**Comment by czyzby** [comment]
Dokka 1.4 fails with out-of-memory errors. It's possible that we have to upgrade the Gradle as well.

**Comment by czyzby** [comment]
Hey @deveth0, are you currently working on this? I want to make a stable release, since there were some crucial dependency updates, and I'd also like the Kotlin Gradle scripts to be merged into the `master` branch. I can wait until the Dokka update if you're working on this issue.

**Comment by deveth0** [comment]
huh? no, not working on this, sorry. Probably you mean somebody else?

**Comment by czyzby** [comment]
Ah, I confused the PRs. I've meant @Megamiun. Sorry. :)

**Comment by Megamiun** [comment]
Oh, @czyzby, I think it is better for you not to wait, I was thinking of starting working on it at the earliest on the next week.

**Comment by czyzby** [comment]
@Megamiun Don't worry, take your time. I've set up automatic deployment of the [Dokka documentation](https://libktx.github.io/ktx/) on the `master` branch. As you can see, it's pretty underwhelming right now, so it might be worth to wait a bit to publish the new docs along with the latest release.

**Comment by czyzby** [comment]
Thanks again for another contribution, @Megamiun!
