### ISSUE TITLE
Add optional Camera / Projectionmatrix to ShapeRenderer.use

### ISSUE THREAD

**Issue by deveth0** [libktx/ktx#313]
`Batch.use` allows to set the Projectionmatrix but ShapeRenderer is missing this parameter. 
To have a consistent API, I'd suggest to allow an optional Camera / Projectionmatrix parameter in ShapeRenderer too.

**Comment by deveth0** [comment]
PR: https://github.com/libktx/ktx/pull/314

**Comment by czyzby** [comment]
Thanks for your contribution, @deveth0! Your changes should be available shortly as a snapshot release.
