### ISSUE TITLE
LibGDX 1.9.13 released

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#330]
LibGDX 1.9.13 was released a few days ago with two breaking changes. 

I think they should not have an impact on LibKTX.

Also, a beta(?) of gdx video is part of that release. Maybe, once it is stable, it is worth a look to check if it is worth to "kotlinize" it.

Just fyi  :)

**Comment by czyzby** [comment]
Thanks, I'll update the project soon.

**Comment by czyzby** [comment]
There were quite a few deprecated methods of `Vector2` and `Vector3`. It only affected the tests though.

**Comment by Quillraven** [comment]
wow - so fast :) 

I will try to update a project of mine this weekend and hopefully the project is not affected by the breaking changes. Let's see! If I don't post again then assume that everything went well.

**Comment by czyzby** [comment]
Thanks.

**Comment by Quillraven** [comment]
After struggling again with IntelliJ and gradle (it seems like android gradle plugin still does not work very well and messes up a lot of things all the time) everything turned out well.

No problems on my end 👍
