### ISSUE TITLE
Add AssetManager#getDiagnostics equivalent to AssetStorage

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#344]
Extend `AssetStorage` with methods that allow to copy and inspect the internal state. Include output formatting.

_Originally posted by @Quillraven in https://github.com/libktx/ktx/discussions/343_

**Comment by czyzby** [comment]
@Quillraven Snapshot release with the functionality should be available shortly. You can use `AssetStorage#takeSnapshot` or `AssetStorage#takeSnapshotAsync` to create a deep copy of the storage state that you can inspect and compare in various stages of the app. Returned `AssetStorageSnapshot` has a `prettyPrint` method that's similar to `AssetManager#getDiagnostics`, but has more information.

I'd appreciate it if you could test it and check if the API is sufficient, so I can do the stable release.

**Comment by Quillraven** [comment]
Awesome, you are always so fast  :)

Will try it today in the evening and let you know.

**Comment by czyzby** [comment]
Thanks. I've noticed there's a small adjustment that I have to make, but the API won't change.

**Comment by Quillraven** [comment]
@czyzby maybe it is again some gradle SNAPSHOT caching issue but can you try if your SNAPSHOT has the new method available? I don't see it on my end using 1.9.14-SNAPSHOT

**Comment by czyzby** [comment]
@Quillraven Just a heads up, calling this method might interfere with loading, as it has to obtain the same lock. I'd avoid overusing this method and do it only for debugging purposes (e.g. inspecting the storage state in various stages of the app).

Aside from the usual Gradle issues, is the API working as expected? Do you need any additional data?

**Comment by Quillraven** [comment]
no that is perfectly fine for me. I only have the log level on debug during development and call the method once when game gets disposed.

once I work on level switching it will get in handy as well to see if assets get correctly unloaded/disposed.

**Comment by czyzby** [comment]
Thanks for testing!
