### ISSUE TITLE
Artemis-ODB module

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#352]
[Artemis-ODB](https://github.com/junkdog/artemis-odb) is a high performance entity-component-system framework. It is a popular alternative to Ashley among libGDX developers. Dedicated support for this framework in KTX is one of the features that often comes up on the libGDX Discord.

The goal of this issue is to prepare a similar module to [`ktx-ashley`](https://github.com/libktx/ktx/tree/master/ashley) with an equal set of utilities for Artemis-ODB.

**Comment by rabbitfr** [comment]
Hi,

Which help do you need ? 

Best regards,

rabbit

**Comment by czyzby** [comment]
@rabbitfr The goal is to prepare a similar module to the [`ktx-ashley`](https://github.com/libktx/ktx/tree/master/ashley), but currently I'm not actively working on any new major KTX features - hence the `help wanted` tag. If you'd like to try creating a similar set of utilities for Artemis-ODB, I can do code review and help along the way with the API design.

**Comment by deviodesign** [comment]
@czyzby I have created extension functions for artemis-odb, similar to ktx-ashley. Currently I'm finishing some of the unit tests and writing documentation. I may need some help with that though.

**Comment by czyzby** [comment]
@deviodesign If you don't mind, you can set up a WIP pull request and I'll leave some comments. Thanks.

**Comment by czyzby** [comment]
Thanks @deviodesign for tackling this, the module will be available in the next stable release.
