### ISSUE TITLE
Auto-injection methods in ktx-inject

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#379]
- [x] Add `ktx-reflect` module with reflection utilities.
  - [x] `@Reflection` annotation that requires `@OptIn` with additional info about LibGDX reflection.
  - [x] `ClassReflection` and `ArrayReflection` API wrappers.
- [x] Add `Context.bindSingleton` method with reified type that uses reflection to find the constructor and inject appropriate components.
- [x] Add `Context.bind` method with reified type that uses reflection to find the constructor and inject appropriate components.

---

The goal of this issue is to extend `ktx-inject` module with reflection-based methods that ease registration of new components.

### Discussed in https://github.com/libktx/ktx/discussions/378

<div type='discussions-op-text'>

<sup>Originally posted by **runt9** September 27, 2021</sup>
First off, thank you so incredibly much for KTX, it's made my first foray into LibGDX in my favorite language an absolute blast!

I've spent the last decade doing full-stack development in Spring and so coming to using ktx-inject for my DI has been different than what I'm used to. I'm getting ready to rewrite most (all?) of my game to prepare the code base for future growth and one of the things that ended up on my list was seeing if there was a way to make DI a bit more automatic like I'm used to in Spring.

After jumping through some Google searches, it seems like the full package/annotation scanning way would add a lot of coding time and also have some startup overhead, so I went with just seeing what I could do to make it to where I didn't have to call a real constructor with many `inject()` calls so I didn't have to go and update the DI registry every time I added or removed an injected field from a class.

Here's the few lines of code I came up with and wanted to throw it out there as a potential option for ktx-inject, even though it's explicitly stated in the readme that it's reflection-free:

```
inline fun <reified Type : Any> Context.autoBindSingleton() = bindSingleton(autoInject<Type>())

inline fun <reified T> autoInject(): T {
    val constructor = T::class.constructors.first()
    val args = constructor.parameters.map { param -> injector.getProvider(param.type.jvmErasure.java)() }.toTypedArray()
    return constructor.call(*args)
}
```

This makes it to where in your `injector.register {` block, you simply call something like `autoBindSingleton<ClassToBind>()` and it will always inject the correct arguments even if you change the order, add or remove some, etc.

This would also open things up to a path-scanning possibility with Reflections, but that's a step I'm not sure I need right now. But I wanted to share the snippet and see if it might be useful for KTX?

I'm sure as I put this game together there will be many more snippets like this I could potentially contribute so expect to see my name around a bit :)</div>

**Comment by runt9** [comment]
@czyzby Awesome, I love it! Happy to see that you liked the idea enough to get it in there almost immediately! I looked through the code and it looks good to me, and is also just another testament to the power of Kotlin. I'll definitely be popping the new version into my game during my rewrite. I look forward to seeing if any of my other ideas end up being a good fit for KTX

**Comment by czyzby** [comment]
Glad you like it, thanks for the suggestion.
