### ISSUE TITLE
Mapper abstract class designed for companion objects of Ashley Components

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#386]
Add an abstract class `Mapper` that automatically obtains `ComponentMapper` for the enclosing `Component` class. Usage example:

```kotlin
class Example: Component {
  companion object : Mapper<Example>()
}

val mapper: ComponentMapper<Example> = Example.mapper
```

**Comment by auraxangelic** [comment]
@czyzby I've haven't been around for a while, but I'm back to some libgdx stuff. Do you still want me to test this?

**Comment by czyzby** [comment]
@auraxangelic Sure, it would be great to confirm that it works on every platform if you have some time. Thanks!
