### ISSUE TITLE
Selection listener for nodes in Trees

### ISSUE THREAD

**Issue by manabreak** [libktx/ktx#398]
Apologies if this feature is already in place; I did browse through the code but couldn't find this feature yet.

I was wondering if it would be possible to add a selection listener for Tree objects. I was thinking of this kind of format:

```
scene2d.visTree {
    visLabel("Foo")
    visLabel("Bar") { node ->
        visLabel("Baz")
    }
    onSelection { node ->
        // Invoked when a node in the tree was clicked
    }
}
```

**Comment by czyzby** [comment]
I don't recall such an extension. If libGDX `Tree` allows to register listeners, it's certainly possible to add this utility.

If you'd like to contribute it, don't hesitate to make a PR. Otherwise I'll look into it in about 2 weeks.

**Comment by manabreak** [comment]
Good to hear! I might look into it this weekend, if I have time.

**Comment by czyzby** [comment]
Thanks for the contribution, @manabreak. The extension method was renamed to `onSelectionChange` and should be available via a snapshot release soon.
