### ISSUE TITLE
Renaming library

### ISSUE THREAD

**Issue by jsorel** [libktx/ktx#400]
Hello,

This is a unusual request but still :
- 'Kotlin extensions for libGDX'  uses the same shortname as Khronos KTX format => KTX
- 'Kotlin extensions for libGDX' uses the same library name as Khronos software => libktx (https://github.com/KhronosGroup/KTX-Software)

This makes is very very confusing when searching the web.

Needless to say Khronos KTX started more then 10 years ago and is an industrial standard, so ... well they won't change name and since your lib is more or less on the same topic (3D) it may become a legal issue at some point.

I can only suggest that your library should really consider changing name to avoid collision.

**Comment by czyzby** [comment]
Hello @jsorel. I agree that the library naming is a bit unfortunate - I was looking for something that incorporated both Kotlin and GDX/libGDX, and I thought that "KTX" sounds good without doing a proper research. Even more confusingly, libGDX supports KTX textures, and this library basically hijacked the Google search for that. Not only that, but also [Android released it's own Kotlin extensions library named KTX](https://developer.android.com/kotlin/ktx), despite both Khonos KTX and libKTX already being two established projects with a similar name, and arguably similar scope (Kotlin extensions of a framework).

That being said, it's probably a bit too late for a library name change, unless it does become a legal issue. I have not been contacted by the Khronos Group so far, unless you are speaking on their behalf. Suddenly renaming the library will lead to even more confusion for the existing and future users of libKTX. In retrospect, I regret choosing the KTX name, but the damage is already done.

Besides, I don't completely agree that the library is on "more or less the same topic", as Khronos KTX is relatively low level texture format&loader, while libKTX is a bunch of high level utilities mostly focused on 2D and general game development. If anything, there's more overlap between libKTX and Android KTX - both are Kotlin extensions for an established framework.

**Comment by jsorel** [comment]
> That being said, it's probably a bit too late for a library name change, unless it does become a legal issue. I have not been contacted by the Khronos Group so far, unless you are speaking on their behalf.

Don't worry, I'm just a backend developer working in Java for the last two decades and moving to Rust, working on a lot of formats (geospatial and image processing) and currently on KTX (a little frustrated to stumble a lot on your lib in the research results).

It's not unusual to have library name change, when a big event happens, like merging with another project. Just think about it when the time comes.

I'm not fan of Kotlin but good luck with your lib ;)

**Comment by czyzby** [comment]
I understand your frustration, but renaming the library is unlikely to help with that in the short term, and it will create a lot of confusion for the existing and potential users of (this) KTX. A lot of existing pages that mention `KTX`/`libKTX` will still be irrelevant to your search, but now they will make it difficult to pinpoint the actual library that they refer to.

Just to give you some perspective, all of these things will likely break, become obsolete, or require updating:
* Maven ID, which will require changes in project setups other than just a version bump.
* Code package, which would require complete deprecation for at least a couple versions and will eventually break all existing projects. This will also break all existing code snippets.
* GitHub tags assigned to projects using KTX, most of which are third-party.
* StackOverflow tag with existing questions.
* libGDX project setup tools that support KTX libraries or project templates (e.g., `gdx-liftoff`).
* Any third-party wikis or tutorials (e.g., `Quillraven/SimpleKtxGame`).
* libGDX Intellij plugin.
* Any historical blog posts, mentions, testimonials, discussions, chats, etc.

Again, I admit that the library name could have been better, but at this point a rename would be a huge blow to the community for no immediate or short-term benefits.
