### ISSUE TITLE
Donations?

### ISSUE THREAD

**Issue by entangledloops** [libktx/ktx#404]
Hi MJ, I don't see any obvious way to contribute a donation to this project, nor can I find any way to contact the owners outside of filing an issue here. Is there a link I missed somewhere?

**Comment by entangledloops** [comment]
Oof, I missed the "Discussions" page. Closing, as this isn't an really an Issue.

**Comment by czyzby** [comment]
Wiki mentions how to you can contact the developers to ask questions about KTX. Discussions are OK (#406), but I'm also pretty active on the libGDX Discord on the `#kotlin` channel.
