### ISSUE TITLE
EntityListener utilities for Ashley

### ISSUE THREAD

**Issue by RedGrapefruit09** [libktx/ktx#409]
- Add an `EntityRemovalListener` for removal-only
- Add an `EntityAdditionListener` for addition-only
- Kotlin lambda utils for similar functionality

**Comment by czyzby** [comment]
The same could be applied to the interface - instead of providing an interface that is basically a no-op listener and gives no guarantees that the user implements the actual logic, we could add `EntityAdditionListener` and `EntityRemovalListener` interfaces with one no-op method implementation instead.

**Comment by RedGrapefruit09** [comment]
Thanks for your feedback! I agree, `EntityAdditionListener` and `EntityRemovalListener` would be better.
I'll make a PR for this in the coming few days, excuse me for the late reply.

**Comment by czyzby** [comment]
No problem, take your time.

**Comment by czyzby** [comment]
I've rewritten some docs and added missing tests for all system extension methods. In general, we should aim for tests of every public API, even if some of them might seem redundant.

Thanks for the contribution @RedGrapefruit09, nice job. It should be available via the snapshot release shortly.

**Comment by RedGrapefruit09** [comment]
> I've rewritten some docs and added missing tests for all system extension methods. In general, we should aim for tests of every public API, even if some of them might seem redundant.
> 
> Thanks for the contribution @RedGrapefruit09, nice job. It should be available via the snapshot release shortly.

Thanks for your corrections!

**Comment by czyzby** [comment]
I think I removed that part since it seemed a bit redundant - all methods are already mentioned in the first section. I can add it as a comment to the code sample, since example sections usually do not provide any API listings.
