### ISSUE TITLE
Coroutines-based asset manager

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#41]
Asynchronous asset loading based on coroutines would both benefit simplify the API usage - it would look as if assets are loaded synchronously - as well as the asset manager internal implementation.

---

It would be possible to turn this pseudocode example:

```Kotlin
fun create() {
  assetManager.apply {
     load<String>("my.txt") // Returns nothing. :C
     load<Texture>("logo.png")
     load<String>("other.txt")
     load<I18NBundle>("i18n.properties")
     // Schedule loading of other assets.
  }
}

fun render() {
  if (assetManager.update()) {
    // Assets loaded!
    finishLoading()
  }
  updateProgressLabel(assetManager.progress)
}

fun finishLoading() {
   assetManager.apply {
     myText = get<String>("my.txt")
     logo = get<Texture>("logo.png")
     otherText = get<String>("other.txt")
     bundle = get<I18NBundle>("i18n.properties")
     // Extract other assets.
  }
  goToNextView()
}
```

...into this pseudocode example:
```Kotlin
fun create() {
  assetManager.apply {
     // Each call suspends and resumes on the rendering thread,
     // never blocking the rendering process.
     myText = load<String>("my.txt")
     logo = load<Texture>("logo.png")
     otherText = load<String>("other.txt")
     bundle = load<I18NBundle>("i18n.properties")
  }
  // Resumes after all assets are loaded:
  goToNextView()
}

fun render() {
  updateProgressLabel(assetManager.statusMessage)
}
```

@kotcrab Thoughts on this? Should we include coroutines in `ktx-assets`, add the new manager to `ktx-async` (general LibGDX asynchronous operations utilities and basic coroutines support) or create a separate module?

**Comment by kotcrab** [comment]
This looks neat but seems only useful if you will use assets in current view. I'm assuming view is some kind of class here. If current view acts as loading screen and then next game view is separate class then you have to retrieve assets again anyway. Depends on how your project is coded of course. I'm not really fan of this extra layer of complexity by suspending create method, calling render until it loads and resuming create method. For me it's counterintuitive to standard gdx app life cycle. 

Let's say you want to do something more in the render method of async example after loading all assets. How could you check if some assets from create method are still not loaded, I think `assetManager.update()` could return true right after loading first assets but before starting loading second one.

As for the module, I think `ktx-assets` is OK, but I guess this can be only done after removing methods using static or it might be confusing which one method is used.

**Comment by czyzby** [comment]
> I'm not really fan of this extra layer of complexity by suspending create method, calling render until it loads and resuming create method. For me it's counterintuitive to standard gdx app life cycle.

Ah, yes, coroutines and asynchronous programming do need some getting used to, but after the "a-ha" moment, it actually simplifies the logic if you use a lot of asynchronous calls. LibGDX `AssetManager` API is really tedious if you think about it and poor when handling individual assets loading. (`finishLoading` for a single asset is implemented by spin-waiting until the asset is loaded. For all you know, all other assets might be loaded before the one you requested.)

Consider this example based on my early implementation of `ktx-async` on my local branch:

```Kotlin
class App : ApplicationAdapter() {
  lateinit var batch: SpriteBatch
  lateinit var font: BitmapFont

  override fun create() {
    enableKtxCoroutines()
    font = BitmapFont()
    batch = SpriteBatch()
    onMainThread {
      val response = httpRequest("http://your.server.com").await()
      println("Server response: ${response.resultAsString}")
      // TODO Process response, change view.
    }
  }

  override fun render() {
    batch.begin()
    font.draw(batch, "Please wait, connecting with the server.", 100f, 100f)
    batch.end()
  }

  override fun dispose() {
    font.dispose()
    batch.dispose()
  }
}
```

This works without blocking the main rendering thread. Compare this with the amount of callbacks you'd have to make when using plain `HttpRequest` LibGDX API.
```Kotlin
    val httpRequest = HttpRequest().apply {
      setUrl("http://example.com")
      setMethod("GET")
    }
    Gdx.net.sendHttpRequest(httpRequest, object : HttpResponseListener {
      override fun cancelled() {
         Gdx.app.postRunnable { throw IllegalStateException() }
      }

      override fun failed(exception: Throwable) {
         Gdx.app.postRunnable { throw exception }
      }

      override fun handleHttpResponse(httpResponse: HttpResponse) {
        Gdx.app.postRunnable {
          // Handle response, change view.
        }
      }
    }
```

> This looks neat but seems only useful if you will use assets in current view.

Why would you think that? Once loaded and assigned to variables, the assets can be passed to other views like any other objects. Beside the flow control, there is nothing magical about coroutines. And the asset manager (whatever we call it) would still keep references to all assets as the official `AssetManager` does, so you could just use `assetManager.get<Texture>("logo.png")` after it is loaded.

> As for the module, I think `ktx-assets` is OK, but I guess this can be only done after removing methods using static or it might be confusing which one method is used.

Not sure if I want `ktx-assets` to depend on both `ktx-async` and official coroutines library, but the module does seem fitting. I guess we'll cross that bridge once we get there.

**Comment by kotcrab** [comment]
> Ah, yes, coroutines and asynchronous programming do need some getting used to

Yeah, probably. I haven't really played with Kotlin's coroutines. I understand the example you provided.

> Why would you think that? Once loaded and assigned to variables, the assets can be passed to other views like any other objects.

Then you will end up with big constructors or setters. My point was that if current view just loads the assets and next view will use standard API to retrieve them again then doing it asynchronous way is very similar to standard one.

**Comment by czyzby** [comment]
> Then you will end up with big constructors or setters.

Not really. If you want to access resources directly from the coroutine-based `AssetManager`, you can. Only the loading phase would be based on coroutines - and simplified in the process, as well as being more easily controlled by the user. After the assets are loaded, there would be virtually no differences between usage of the KTX and LibGDX asset managers. If you want to pass assets in bulk through the manager, it would be just as simple.

Actually, _you_ choose which resources are loaded when in which order, as opposed to just scheduling loading and hoping for the best. It is much easier to load _some_ resources and use them right away, while the others are still being loaded. This usually required workarounds (like two separate managers for immediately loaded assets and asynchronously loaded ones in Autumn MVC - there was simply no other way to affect asset loading order).

Anyway, this would be entirely optional to use. I don't want to throw coroutines at every problem LibGDX faces, so don't worry - no breaking changes incoming. I still think you'll see the benefits after you play around with the API once it's complete.

**Comment by czyzby** [comment]
`AssetStorage` - lightweight coroutines-based alternative to `AssetManager` is already available in the snapshot release and on the `develop` branch. @kotcrab @raincole @sreich Thoughts?

**Comment by raincole** [comment]
Looks neat. Some thoughts:

* It doesn't handle reference counting. If this is intentional, there should be a warning in docs otherwise it's bound to surprise some users. But I suggest we add it later, because(at least for me) reference counting is a very useful feature.
* Also I'm against `AssetManagerWrapper`. It's hard to ensure that `AssetStorage` has the same behavior as `AssetManager` does. And I don't like a subclass that can't be used as its superclass. If one wants to use `AssetStorage`,  he can go for it and take the risk, not use `AssetManagerWrapper` and assume it's some kind of `AssetMananger`.
* (minor) Since we have `TextureLoader`, how about `JsonLoader`? I can't remember the last time I loaded unformatted text as a string.
* (minor) I feel we should only use backtick strings for actual test names. For example, this snippet:

```
  fun `should return loaded asset if trying to load the same asset`()
      = `coroutine test`(concurrencyLevel = 1) { ktxAsync -> ....
    }
  }
```

Looks kinda weird to me. `` `coroutine test` `` is a utility function rather than a test and I think `coroutineTest` reflects this fact better.

**Comment by czyzby** [comment]
> * It doesn't handle reference counting.

Nope. It just loads dependencies recursively, it doesn't maintain any kind of dependencies graph. That's the beauty of it - comparing the implementation to the `AssetManager`, it's dead simple and easy to follow.

Might I ask what do you use references counts for? I can imagine it might be pretty useful for debugging, but are there any other practical uses?

> * Also I'm against `AssetManagerWrapper`.

Believe me, I'm also against this approach, but note that this is _not_ a public API: this is an internal class that makes `AssetStorage` compatible with existing `AssetLoader` implementations. LibGDX `AssetLoader` API enforces usage of `AssetManager`, so wrapping `AssetStorage` seemed like a better idea than rewriting all LibGDX loaders.

KTX users should not access `AssetManagerWrapper` directly, it's just out there to support LibGDX API.

> * (minor) Since we have `TextureLoader`, how about `JsonLoader`?

I don't see why not, although it would probably need a separate loading method, as the deserialized JSON objects can have different types. So, instead of `load<MyDataObject>` you'd call `loadJson<MyDataObject>`.

> * (minor) I feel we should only use backtick strings for actual test names.

A matter of preference. Backticks methods would be pretty messy in regular code, but I find them very readable in tests. I use backticks for test names and test templates - `` `coroutine test` `` is a good example of a test template that handles some assertions and test lifecycle.

**Comment by czyzby** [comment]
See #66, JSON loading will be supported in `1.9.6-b3`.

**Comment by raincole** [comment]
> Might I ask what do you use references counts for? I can imagine it might be pretty useful for debugging, but are there any other practical uses?

In my particular case, I have a JSON like this:

```
[
  {
    "name": "stage1",
    "assets": [
      { "path": "foo.png", "type": "Texture" },
      { "path": "bar.wav", "type": "Sound" }, ...
    ]
  },
  {
    "name": "stage2",
    "assets": [
      { "path": "meh.png", "type": "Texture" },
      { "path": "bar.wav", "type": "Sound" }, ...
    ]
  },
  ...
```

I load assets that used by stage2 while the player is playing stage1. And I release assets that used stage1 when the player finishes stage1. Without reference counting, it will dispose of `bar.wav` prematurely. 

Another use case is that I have two custom shaders that use texture as their "constants"(the alpha values of the glowing edge). I put their texture in the same png, but I don't' use TextureAtlas. Instead, I have two custom assets whose dependencies are basically `{shader1, texture}` and `{shader2, texture}`. If I dispose of one of them, without reference counting, the texture will be disposed of prematurely.

>  this is an internal class ...

Ahh, okay. Didn't notice that!

> JSON objects can have different types

Maybe the destination class can be a field of `JSONLoaderParameter`? I'm not sure if it's a good idea tho.

> A matter of preference.

Yeah, I don't have a strong opinion about it if the naming is consistent.

**Comment by czyzby** [comment]
> I load assets that used by stage2 while the player is playing stage1. And I release assets that used stage1 when the player finishes stage1. Without reference counting, it will dispose of `bar.wav` prematurely.

Right. When you dispose of a `TextureAtlas`, you expect all of its `Texture` instances to be disposed. You're right, this is an issue that `AssetStorage` has to address.

> Maybe the destination class can be a field of `JSONLoaderParameter`? I'm not sure if it's a good idea tho.

Not really, as all JSON data objects would have to extend the same class or set the loader to multiple classes in order to make it work with the current API.

**Comment by czyzby** [comment]
#69
