### ISSUE TITLE
Upgrade to LibGDX 1.11.0

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#415]
See the [blog post](https://libgdx.com/news/2022/05/gdx-1-11).

**Comment by Quillraven** [comment]
Hi,

I recently saw a Kotlin `error` utility function:

```kotlin
/**
 * Throws an [IllegalStateException] with the given [message].
 *
 * @sample samples.misc.Preconditions.failWithError
 */
@kotlin.internal.InlineOnly
public inline fun error(message: Any): Nothing = throw IllegalStateException(message.toString())
```

I think it would be worth adding a `gdxError` function to maybe ktx-app module that throws a GdxRuntimeException. What do you think?
Could be part of this 1.11 upgrade ;)

**Comment by czyzby** [comment]
Sure, seems easy enough. I'll add it while bumping the version.

**Comment by czyzby** [comment]
I've decided to add it to the `ktx-app` module, since there isn't one dedicated to error handling or misc utilities. It should be available shortly as `1.11.0-SNAPSHOT`.

**Comment by Quillraven** [comment]
Should it be already available? Because at least I cannot download it :(

**Comment by czyzby** [comment]
You're right, it failed while trying to resolve the Box2D dependency. I've scheduled the jobs to rerun, hopefully it's available now.

```kotlin
 > Error while evaluating property 'filteredArgumentsMap' of task ':box2d:compileKotlin'
   > Could not resolve all files for configuration ':box2d:compileClasspath'.
      > Could not find gdx-box2d-1.11.0.jar (com.badlogicgames.gdx:gdx-box2d:1.11.0).
        Searched in the following locations:
```

**Comment by czyzby** [comment]
Honestly, I'm not sure what's the issue. I think it might have something to do with the `compileOnly` dependencies no longer working in CI environment. I'll try to change them to `api`/`implementation` dependencies where appropriate.

**Comment by czyzby** [comment]
@Quillraven I'm still not entirely sure what was the issue, but it seems like a combination of missing dependencies that might have been cached back before JCenter was removed, compile-only scopes, and some newer libGDX modules being not available yet for the CI for some reason? Anyway, the snapshot should be available shortly.

**Comment by Quillraven** [comment]
thank you, it is now working for me! :)
