### ISSUE TITLE
Scene2D stage.actors not working properly?

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#433]
Most likely I am doing something wrong but I don't understand why this code is working

```kotlin
stage.addActor(scene2d.table {
            setFillParent(true)
            label("Test")
        })
```

and this one isn't

```kotlin
stage.actors {
            scene2d.table {
                setFillParent(true)
                label("Test")
            }
        }
```

Shouldn't `actors` be the same as `addActor` according to the documentation? When I debug it, it looks like `actors` is not adding the table to the root of the stage because it shows me 0 children. Italso seems like I never reach the `storeActor` method of the `StageWidget` which would explain why it doesn't work but I don't understand why `storeActor` isn't called.

**Comment by Quillraven** [comment]
nevermind ... I just saw I need to remove the `scene2d.` prefix in the second version, then it works.

**Comment by czyzby** [comment]
@Quillraven `scene2d` object usage is necessary only for top-level widgets without a parent - for example, it should have been used if you wanted to assign the table to a variable and add it to a stage later on. `stage.actors` gives full access to the DSL without the need for `scene2d` object. In that case, this prefix is not only unnecessary, but will actually prevent the created actors to be added to the immediate parent (i.e., `Stage` main widget group).

**Comment by Quillraven** [comment]
I think it is fine and that's why I found it out myself a little bit later. I was confused about the wording "root actor" that is used in the documentation. I like your explanation here better. At least for me it makes it easier to understand.

scene2d. prefix to store the actor in a variable and add it manually to another widget.

No prefix if inside a Scene2d DSL to add the actor directly to the current widget in scope.

Thank you for the clarification 🤗

**Comment by czyzby** [comment]
I'll try to add another paragraph with a clarification. Thanks for raising the issue.

**Comment by czyzby** [comment]
@Quillraven I've added another code example to illustrate this issue, thanks again for reaching out.
