### ISSUE TITLE
Dependency mismatch with VisUI and libGDX

### ISSUE THREAD

**Issue by manabreak** [libktx/ktx#440]
It seems that ktx is dependent on libgdx version 1.11.0 and VisUI version 1.5.0. However, VisUI 1.5.1-SNAPSHOT should be used with libgdx version 1.11.0.

**Comment by czyzby** [comment]
Stable releases should not depend on snapshots. VisUI test suites did not report any API incompatibilities, so it should be fine. You can override the VisUI version in your project if you'd like to use the snapshots.

**Comment by czyzby** [comment]
The next KTX release will include VisUI 1.5.1, which supports libGDX 1.11.0.
