### ISSUE TITLE
Unable to load assets in HeadlessApplication

### ISSUE THREAD

**Issue by ronjunevaldoz** [libktx/ktx#441]
I'm not sure if loading assets via HeadlessApplication is supported. I tried the below example to load assets via ktx-async and AssetStorage. Assume that this was working in desktop mode.

```kotlin
if(Gdx.files.internal("data/model/test.gltf").exists()) {
   println("exists")
}
// exists
 ```

```kotlin
// onCreate
 KtxAsync.launch {
   setLoader(".gltf") { GLTFAssetLoader() }
   load<SceneAsset>("data/model/test.gltf")
}
```

Encountered error
```ktx.assets.async.AssetLoadingException: Unable to load asset:  data/model/test.gltf```

**Comment by czyzby** [comment]
It's not supported. You'll notice that the whole [Graphics](https://github.com/libgdx/libgdx/blob/gdx-parent-1.10.0/backends/gdx-backend-headless/src/com/badlogic/gdx/backends/headless/mock/graphics/MockGraphics.java) class has a mock implementation on the headless platform. If you'd like to load assets with a headless application, try launching the desktop backend without a window.
