### ISSUE TITLE
Question about new additions

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#479]
Hi,

I am currently doing another project with LibGDX/LibKTX and I missed a few extensions that I implemented now myself but I could also make them a contribution to LibKTX if needed.
The things I am missing:
- destructor operators for certain "math" shapes like Rectangle, Ellipse, ...
- a `use` extension for TiledMap renderer (similar to what we have for batch)

Is that something useful? Or do you think that should not be part of LibKTX?

Rectangle example:

```kotlin
operator fun Rectangle.component1(): Float = this.x
operator fun Rectangle.component2(): Float = this.y
operator fun Rectangle.component3(): Float = this.width
operator fun Rectangle.component4(): Float = this.height
```

**Comment by czyzby** [comment]
Sure, these could be added to `ktx-math` and `ktx-tiled` respectively. Would you like to submit a PR?

**Comment by Quillraven** [comment]
Yes, I will try to create one over the weekend :)
