### ISSUE TITLE
SNAPSHOT download no longer working?

### ISSUE THREAD

**Issue by Quillraven** [libktx/ktx#486]
Hi,

for whatever reason my GitHub actions can no longer download the SNAPSHOT version of LibKTX. I need the SNAPSHOT version because the stable version does not contain the latest tiled extensions.

![image](https://github.com/user-attachments/assets/2ab0f07c-94df-45fd-b940-e900b5add666)

Is something wrong on my end? Or is there something broken with the SNAPSHOT version?

[Here](https://github.com/Quillraven/Masamune) is the example project link.

**Comment by Quillraven** [comment]
nevermind, upgraded Gradle from 8.8 to 8.9 and now it is working again. No idea why this is happening but I had the same issue a few days ago. For whatever reason it seems to be not stable to get the SNAPSHOT version.

Maybe a Gradle 8.8 issue?

**Comment by czyzby** [comment]
No clue what caused this, but the snapshots were not removed.

**Comment by Quillraven** [comment]
I had the same problem locally a few days ago and also verified on sonatype repo if snapshots are there. After some time it just worked again and I blamed some local caching issues for it.

Yesterday it happened via the GitHub action though which always starts from zero I guess and has no locally cached Gradle stuff. That is weird 😅

I will monitor it and if it happens again I think it is better to open an issue for the Gradle devs? Looks like it is not a ktx issue if the snapshot jars are there and you did not change anything.
