### ISSUE TITLE
Collection operations that return Gdx collections directly

### ISSUE THREAD

**Issue by raincole** [libktx/ktx#58]
Let's say I'm `map`ping a `GdxArray`:

```
val people = gdxArrayOf(Person("Alice"), Person("Bob"))
val names = people.map { it.name }
```

`names` will be a kotlin `List` because `Iterable#map` returns `List`. To get a `GdxArray` I have to call `toGdxArray`. But isn't the whole reason I use `GdxArray` to avoid object creation? 😧 

There seems to be no way to make Kotlin smart enough to build a GdxArray automatically(something like Scala's `canBuildFrom`). Therefore, I'd suggest extension methods like `Iterable#mapGdx`, `Iterable#filterGdx` to make things easier.

I'm willing to write these code and make a PR,  but before I jump into my editor I want to discuss whether it's a good idea.

**Comment by czyzby** [comment]
I'm aware of this issue - completely copying the _stdlib_ API seemed like an overkill for most cases. I don't mind reviewing the code and including this in `gdx-collections` if you're willing to write it, but just know that it can be really time-consuming to cover all operations.

Anyway, `Gdx` suffix is not necessary. For example `GdxArray.map` would override `Iterable.map` method, as long as you keep the `ktx.collections.*` import around. We're already doing this for operator overloading - we'll just add a warning in the `README` file.

**Comment by czyzby** [comment]
It's a shame that LibGDX collections share no common interface. If you want to write such extensions for _all_ collections,  there will be a lot of code duplication.

Common and basic LibGDX collections:
- `Array`
- `ObjectSet`
- `ObjectMap`

Useful, but rarely used collections:
- `IdentityMap`
- `OrderedMap`
- `OrderedSet`
- `SnapshotArray`

Optimized primitives collections:
- `BooleanArray`
- `ByteArray`
- `CharArray`
- `FloatArray`
- `IntArray`
- `IntFloatMap`
- `IntIntMap`
- `IntMap`
- `IntSet`
- `LongArray`
- `LongMap`
- `ObjectFloatMap`
- `ObjectIntMap`

Others:
- `ArrayMap`
- `BinaryHeap`
- `Bits`
- `DelayedRemovalArray`
- `PooledLinkedList` (replaced with KTX `PooledList`)
- `Queue`
- `SortedIntList`

**Comment by raincole** [comment]
I don't plan to rewrite every method tho. Even only `map`, `filter` and probably `flatten` can cover most use cases.

That being said, the number of collections is still much more than I thought! Maybe just do it for `Array`, `ObjectSet` and `ObjectMap` for now?

**Comment by czyzby** [comment]
> Maybe just do it for Array, ObjectSet and ObjectMap for now?

Agreed, but it would be nice if you also added extensions for `PooledList` (`LinkedList` equivalent).

**Comment by czyzby** [comment]
Just giving you a heads up: `master` branch is basically "frozen" from now on and updated only on releases. Create new pull requests to the `develop` branch.

**Comment by czyzby** [comment]
@raincole Any updates on this? If you already started on your branch, I can help you out. It would be great to list the extension methods that you'd like to include in each collection.

**Comment by raincole** [comment]
Well I haven't even started. Just too busy with my day job. I plan to start it this weekend tho.

**Comment by czyzby** [comment]
It's OK, take your time.

**Comment by czyzby** [comment]
Thanks. Snapshot with your changes is already uploaded.

**Comment by czyzby** [comment]
Just wanted to say that your utilities are already uploaded in the `1.9.6-b4` release.
