### ISSUE TITLE
Box2D API extensions

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#65]
- [x] `Joint` building utilities.
- [x] Callbacks API: ability to access built `Body` and `Fixture` instances from within building blocks through callbacks invoked after `World.createBody`/`Body.createFixture`.

---

#52

**Comment by czyzby** [comment]
@Jkly I've implemented the callbacks API, as well as `Joint` factory methods. I'm planning on releasing `1.9.6-b3` version today and I'd appreciate it if you tried to refactor at least some parts of your Box2D application to use the new `ktx-box2d` module. Additional feedback would be great at this point. Again, thanks for your review of this library.

**Comment by Jkly** [comment]
@czyzby I've managed to port over to `ktx-box2d` with no issues - I've found equivalents for everything I used to do in `gdx-box2d-kotlin`, and I like the `onCreate` callback style as the intent is clearer and reads nicely. The module looks good from my point of view 👍
