### ISSUE TITLE
References counting and dependencies management in AssetStorage

### ISSUE THREAD

**Issue by czyzby** [libktx/ktx#69]
- [x] Store collection of dependencies' paths of each asset.
- [x] Count references to each asset. User action (explicit loading of an asset) should increase its reference count by 1.
- [x] Recursively dispose of assets' dependencies if their reference count reaches 0.
- [x] Improve multi-coroutine scheduling of asset loading.

---

Currently `AssetStorage` is not aware of assets' dependencies, which might lead to unexpected behavior during disposing - you can dispose a particular asset with a single operation, but none of its dependencies.

**Comment by czyzby** [comment]
@raincole I believe the reference counting issues are now resolved. You can extract reference counts and dependencies lists from the `AssetStorage`. Upon asset unloading, all of its dependencies' reference counts are decremented recursively - if a dependency reaches 0 references, it is unloaded. Can you review the changes?

**Comment by czyzby** [comment]
Yes, there's a warning about loading the same asset twice at the same time. The root of the issue is not the amount of threads used by the executor, but they asynchronous nature of assets loading itself. To be fair, both `AssetStorage` and `AssetManager` would throw a runtime exception in such case.

However, unless the same asset is scheduled for loading at the _same frame_ in two separate coroutines, this is not an issue - both `load(A)` and `unload(A)` are _always_ executed on the main rendering thread, so if an asset is already loaded and you call `load` on it, you'll simply increase its references count and have it returned instantly. The exception occurs only if you're unfortunate enough to have an asynchronous loading task scheduled both times you call `load`.

I guess we could improve the multi-coroutine safety by introducing suspensions if an asset is already scheduled for loading - if your asset is already loaded by a separate coroutine, wait until it is finished. I can check if it can be done without major refactoring.

Is the reference counting implementation sufficient for your use case?

**Comment by czyzby** [comment]
@raincole I believe I've nailed it, sir. If an asset is already scheduled for loading by another coroutine, your coroutine is suspended and waits for the other to finish loading this particular asset. Then it resumes with its own loading. This means you can `load` and `unload` the same asset on any amount of parallel coroutines launched at the same time and it will not break. (Well, as long as you call `unload` on the main rendering thread or within a `KtxAsync` coroutine's body, but it should not be an issue.)

Is there anything else you can think of that needs to be addressed?

**Comment by raincole** [comment]
You're right, there is no race condition on `referenceCounts`. I've confounded `ktxAsync` with `KtxAsync.asynchronous`. The current implementation looks great.

One nitpicking on doc:


> *Loading same asset multiple times* | **Supported**. `load` and `unload` can be called with the same asset path multiple times on multiple coroutines at the same time. Coroutines are suspended until the asset is loaded if another thread is already handling the loading of requested asset. Thanks to references counting, assets are not fully disposed of until `unload` is called the same amount of times as `load`. | **Not supported.** Trying to load the same asset multiple times causes a runtime exception.


It's quite misleading? `AssetManager` actually can only load the topmost task in the stack, so it can't actually load the same asset multiple times at the same time. If one wants to shoot its own foot, he needs to use multiple `AssetManager`s. And if he does so with multiple `AssetLoader`s his foot will be shot as well.

I'd suggest some wordings like:

> *Loading multiple assets concurrently* | **Supported** Supported by using multiple coroutines and concurrencyLevel > 1 | **Not supported.** `update()` loads assets one by one.

> *Loading same asset multiple times* | **Supported** Loading the same asset again only increases its reference count. If the requested asset is loading by another coroutine, the coroutine suspends until it's loaded.  | **Supported** Loading the same asset again only increases its reference count.

**Comment by czyzby** [comment]
> `AssetManager` actually can only load the topmost task in the stack, so it can't actually load the same asset multiple times at the same time.

You're right, I've been reading `AssetManager` sources lately and I was pretty sure I've seen an exception with `"Asset is already loaded (...)"` message, but that must have been thrown only if the asset class is incompatible. I'll update the documentation and remove the `Loading same asset multiple times` point.

**Comment by czyzby** [comment]
Tests were a pain to write, but I believe `AssetStorage` is fully usable at this moment. Thanks for the review.

@raincole If you don't mind using the snapshot releases and doing a little bit of refactoring, I'd love to hear some feedback of using `AssetStorage` in an actual application before the next release. I think I've finished everything I wanted for `1.9.6-b3` (maybe except #65 if it's not too much work), so I'll probably release the next beta version this weekend.

**Comment by czyzby** [comment]
@raincole There. Now it should count references consistently with `AssetManager`. Thanks again for the review - I'd release the next version with non-feature-complete `AssetStorage` if it weren't for your suggestions.

**Comment by raincole** [comment]
Glad I helped 😀 
I don't think I'll have time to refactor my code this week though. (Plus it's hardly an actual application, but a bunch skeleton code waiting for lazy me to work on...)
