### ISSUE TITLE
Assignment operators in math library

### ISSUE THREAD

**Issue by molikto** [libktx/ktx#81]
Great library!

But imho the operator overload should use the plusAssign etc. not plus

https://kotlinlang.org/docs/reference/operator-overloading.html#assignments

Then create new operators `plus` etc. that will create a new vector each time. 

What's your opinion? 

LibGDX use mutable vector for performance reasons, but + doesn't behave expected for functional minded programmers

**Comment by molikto** [comment]
Nevermind, just noticed that Kotlin cannot override both `plus` and `plusAssign`

**Comment by czyzby** [comment]
Yeah, when you override `+`, you get `+=` for free. I don't think these two should have drastically different implementation, and - with KTX being just a wrapper over LibGDX - we stick to LibGDX way of doing things. Even if it means mutability. See #29.

**Comment by czyzby** [comment]
Turns out you can override both, at least in `1.2`. Assignment operators now mutate vector/matrix instances, while regular binary operators create new instances for the result. See #130.
