### ISSUE TITLE
Creating a new Table with expanded cells

### ISSUE THREAD

**Issue by amitkot** [libktx/ktx#93]
I'm creating a Table with expanded cells. I wrote it without ktx:
```kotlin
Table().apply {
  setFillParent(true)
  
  add(TextButton("Tutorial", skinny).apply {
    onClick { doSomething() }
  }).expand()
  
  row()
  
  add(TextButton("Play", skinny).apply {
    onClick { doSomething()        
  }).expand()
}
```

Trying to use ktx for it, I could not access the cells that were created, to call ```expand()``` on.

Any ideas?

By the way, thanks for a great library!

**Comment by czyzby** [comment]
Check the [Scene2D examples section](https://github.com/libktx/ktx/tree/master/scene2d#usage-examples). You can access the table cells in two ways:

```kotlin
// 1. Widget's building block lambda parameter:

table {
  button {
    it.expand()
  }
  button { cell ->
    cell.expand()
  }
}

// 2. `cell` extension method:

table {
  button().cell(expand = true)
  button {
    // ...
  }.cell(expand = true)
}
```

**Comment by amitkot** [comment]
I missed it in the docs. Thanks!
