### ISSUE TITLE
Consider Providing an option for variable frame rate in KtxGame

### ISSUE THREAD

**Issue by amitkot** [libktx/ktx#95]
I'm developing a game for Android.
In my game I have a wheel that rotates with an adjustable speed.
When switching to Use ```KtxGame``` as my game's base class, the wheel actor started stuttering ([video](https://drive.google.com/open?id=0B5mXjA1yTx25UUhSNVZRY2t5a1U)).

After disabling the fixed step mechanism the rotation is smooth again ([video](https://drive.google.com/open?id=0B5mXjA1yTx25U1RQay1mdmFfUDQ)).

Code:
```kotlin
abstract class KotlinApplication(protected val fixedTimeStep: Float = 1f / 60f,
                                 protected val maxDeltaTime: Float = 1f) : ApplicationListener {

...

    override final fun render() {
        clearScreen(0f, 0f, 0f, 1f)
        render(Gdx.graphics.deltaTime)
//        timeSinceLastRender = Math.min(timeSinceLastRender + Gdx.graphics.rawDeltaTime, maxDeltaTime)
//        while (timeSinceLastRender >= fixedTimeStep) {
//            timeSinceLastRender -= fixedTimeStep
//            clearScreen(0f, 0f, 0f, 1f)
//            render(fixedTimeStep)
//        }
    }
```

It might be because Android does extra calculations to "smooth" the deltaTime?

```java
// AndroidGraphics.java
...
	@Override
	public float getDeltaTime () {
		return mean.getMean() == 0 ? deltaTime : mean.getMean();
	}
```

I tried debugging it and have no better idea for now.
What is your opinion?
Should I submit a patch?

Thanks!

**Comment by czyzby** [comment]
Can you reproduce the issue on desktop - preferably using a different frame rate or rendering more sprites, so the effect is visible? It's entirely possible that Android reports frame rate differently and already implements some kind of smoothing.

**Comment by amitkot** [comment]
It happens on the desktop as well.
I created an [example project](https://github.com/amitkot/ktx-fixed-time-step) to demonstrate this issue.

**Comment by OsipXD** [comment]
I have same problem when i extend KotlinApplication class. Looks like this feature works wrong.
Video here: [with KTX](https://youtu.be/pimwpX9Qx_w), [without KTX](https://youtu.be/AjWcCo9zdFA)
[Source Code](https://github.com/OsipXD/NightMuseumCat)

**Comment by czyzby** [comment]
Yeah, looks like it. I'll remove the fixed frame rate utilities.

**Comment by OsipXD** [comment]
Maybe there are another way to do it?
I think, it causes only when real frame rate higher than fixed. Because when I tried to catch this bug in debug mode it didn't.
I also tried to change `while` to `if` the animation became a little smoother.

**Comment by czyzby** [comment]
It seems to be causing more issues than it solves. I think the problems that it might solve are not common enough to justify such implementation of a core `ktx-app` class. I'll remove `KotlinApplication` and update implementation of `KtxGame`.

**Comment by OsipXD** [comment]
Ok, thanks anyway

**Comment by czyzby** [comment]
@amitkot @OsipXD I removed the fixed rendering time steps support in the latest commit. Can you use the `1.9.6-SNAPSHOT` version of `ktx-app` and see if the issue is fixed? If it's OK, I'll release the next beta version, since this is a breaking change and I've updated some major dependencies (including Kotlin stdlib/coroutines).

**Comment by OsipXD** [comment]
Yes, it's fixed!

**Comment by czyzby** [comment]
Great, thanks. Expect `1.9.6-b7` release later today.
